// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Re-exports the generated OpenEngine (`openengine.v1`) gRPC types.
//!
//! Generated by `build.rs` from the vendored contract in `proto/`; see
//! `proto/README.md` for the upstream revision.

#![allow(clippy::all)]
#![allow(missing_docs)]

tonic::include_proto!("openengine.v1");
