// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by capnpc-go. DO NOT EDIT.

package gbuildmanifestcapnpv2

import (
	capnp "capnproto.org/go/capnp/v3"
	math "math"
	strconv "strconv"
)

// Constants defined in gbuild_manifest.capnp.
const (
	CurrentContractRevision = uint32(2)
)

type Manifest capnp.Struct

// Manifest_TypeID is the unique identifier for the type Manifest.
const Manifest_TypeID = 0xdfeff145e86a5a8f

func NewManifest(s *capnp.Segment) (Manifest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return Manifest(st), err
}

func NewRootManifest(s *capnp.Segment) (Manifest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return Manifest(st), err
}

func ReadRootManifest(msg *capnp.Message) (Manifest, error) {
	root, err := msg.Root()
	return Manifest(root.Struct()), err
}

func (s Manifest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Manifest) DecodeFromPtr(p capnp.Ptr) Manifest {
	return Manifest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Manifest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Manifest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Manifest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Manifest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Manifest) Model() (ModelInfo, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ModelInfo(p.Struct()), err
}

func (s Manifest) HasModel() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Manifest) SetModel(v ModelInfo) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewModel sets the model field to a newly
// allocated ModelInfo struct, preferring placement in s's segment.
func (s Manifest) NewModel() (ModelInfo, error) {
	ss, err := NewModelInfo(capnp.Struct(s).Segment())
	if err != nil {
		return ModelInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Manifest) Deployment() (DeploymentInfo, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return DeploymentInfo(p.Struct()), err
}

func (s Manifest) HasDeployment() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Manifest) SetDeployment(v DeploymentInfo) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewDeployment sets the deployment field to a newly
// allocated DeploymentInfo struct, preferring placement in s's segment.
func (s Manifest) NewDeployment() (DeploymentInfo, error) {
	ss, err := NewDeploymentInfo(capnp.Struct(s).Segment())
	if err != nil {
		return DeploymentInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Manifest) Artifacts() (ArtifactInfo, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return ArtifactInfo(p.Struct()), err
}

func (s Manifest) HasArtifacts() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Manifest) SetArtifacts(v ArtifactInfo) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewArtifacts sets the artifacts field to a newly
// allocated ArtifactInfo struct, preferring placement in s's segment.
func (s Manifest) NewArtifacts() (ArtifactInfo, error) {
	ss, err := NewArtifactInfo(capnp.Struct(s).Segment())
	if err != nil {
		return ArtifactInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Manifest) Reserved3() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(3)
}

func (s Manifest) HasReserved3() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Manifest) SetReserved3(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(3, v)
}
func (s Manifest) ContractRevision() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s Manifest) SetContractRevision(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

// Manifest_List is a list of Manifest.
type Manifest_List = capnp.StructList[Manifest]

// NewManifest creates a new list of Manifest.
func NewManifest_List(s *capnp.Segment, sz int32) (Manifest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[Manifest](l), err
}

// Manifest_Future is a wrapper for a Manifest promised by a client call.
type Manifest_Future struct{ *capnp.Future }

func (f Manifest_Future) Struct() (Manifest, error) {
	p, err := f.Future.Ptr()
	return Manifest(p.Struct()), err
}
func (p Manifest_Future) Model() ModelInfo_Future {
	return ModelInfo_Future{Future: p.Future.Field(0, nil)}
}
func (p Manifest_Future) Deployment() DeploymentInfo_Future {
	return DeploymentInfo_Future{Future: p.Future.Field(1, nil)}
}
func (p Manifest_Future) Artifacts() ArtifactInfo_Future {
	return ArtifactInfo_Future{Future: p.Future.Field(2, nil)}
}
func (p Manifest_Future) Reserved3() *capnp.Future {
	return p.Future.Field(3, nil)
}

type ModelInfo capnp.Struct

// ModelInfo_TypeID is the unique identifier for the type ModelInfo.
const ModelInfo_TypeID = 0xf647409b6c50c2b2

func NewModelInfo(s *capnp.Segment) (ModelInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ModelInfo(st), err
}

func NewRootModelInfo(s *capnp.Segment) (ModelInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ModelInfo(st), err
}

func ReadRootModelInfo(msg *capnp.Message) (ModelInfo, error) {
	root, err := msg.Root()
	return ModelInfo(root.Struct()), err
}

func (s ModelInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ModelInfo) DecodeFromPtr(p capnp.Ptr) ModelInfo {
	return ModelInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ModelInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ModelInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ModelInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ModelInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ModelInfo) Arch() (ArchConfig, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ArchConfig(p.Struct()), err
}

func (s ModelInfo) HasArch() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ModelInfo) SetArch(v ArchConfig) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewArch sets the arch field to a newly
// allocated ArchConfig struct, preferring placement in s's segment.
func (s ModelInfo) NewArch() (ArchConfig, error) {
	ss, err := NewArchConfig(capnp.Struct(s).Segment())
	if err != nil {
		return ArchConfig{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ModelInfo) Tokenizer() (TokenizerInfo, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return TokenizerInfo(p.Struct()), err
}

func (s ModelInfo) HasTokenizer() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ModelInfo) SetTokenizer(v TokenizerInfo) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewTokenizer sets the tokenizer field to a newly
// allocated TokenizerInfo struct, preferring placement in s's segment.
func (s ModelInfo) NewTokenizer() (TokenizerInfo, error) {
	ss, err := NewTokenizerInfo(capnp.Struct(s).Segment())
	if err != nil {
		return TokenizerInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// ModelInfo_List is a list of ModelInfo.
type ModelInfo_List = capnp.StructList[ModelInfo]

// NewModelInfo creates a new list of ModelInfo.
func NewModelInfo_List(s *capnp.Segment, sz int32) (ModelInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[ModelInfo](l), err
}

// ModelInfo_Future is a wrapper for a ModelInfo promised by a client call.
type ModelInfo_Future struct{ *capnp.Future }

func (f ModelInfo_Future) Struct() (ModelInfo, error) {
	p, err := f.Future.Ptr()
	return ModelInfo(p.Struct()), err
}
func (p ModelInfo_Future) Arch() ArchConfig_Future {
	return ArchConfig_Future{Future: p.Future.Field(0, nil)}
}
func (p ModelInfo_Future) Tokenizer() TokenizerInfo_Future {
	return TokenizerInfo_Future{Future: p.Future.Field(1, nil)}
}

type TokenizerInfo capnp.Struct

// TokenizerInfo_TypeID is the unique identifier for the type TokenizerInfo.
const TokenizerInfo_TypeID = 0xa26e80e8f5cd8871

func NewTokenizerInfo(s *capnp.Segment) (TokenizerInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return TokenizerInfo(st), err
}

func NewRootTokenizerInfo(s *capnp.Segment) (TokenizerInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return TokenizerInfo(st), err
}

func ReadRootTokenizerInfo(msg *capnp.Message) (TokenizerInfo, error) {
	root, err := msg.Root()
	return TokenizerInfo(root.Struct()), err
}

func (s TokenizerInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TokenizerInfo) DecodeFromPtr(p capnp.Ptr) TokenizerInfo {
	return TokenizerInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TokenizerInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TokenizerInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TokenizerInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TokenizerInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TokenizerInfo) Path() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s TokenizerInfo) HasPath() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TokenizerInfo) PathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s TokenizerInfo) SetPath(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s TokenizerInfo) StopTokens() (capnp.UInt32List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.UInt32List(p.List()), err
}

func (s TokenizerInfo) HasStopTokens() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TokenizerInfo) SetStopTokens(v capnp.UInt32List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewStopTokens sets the stopTokens field to a newly
// allocated capnp.UInt32List, preferring placement in s's segment.
func (s TokenizerInfo) NewStopTokens(n int32) (capnp.UInt32List, error) {
	l, err := capnp.NewUInt32List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt32List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s TokenizerInfo) Reserved2() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(2)
}

func (s TokenizerInfo) HasReserved2() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s TokenizerInfo) SetReserved2(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(2, v)
}
func (s TokenizerInfo) VocabSize() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s TokenizerInfo) SetVocabSize(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s TokenizerInfo) Reserved4() uint16 {
	return capnp.Struct(s).Uint16(4)
}

func (s TokenizerInfo) SetReserved4(v uint16) {
	capnp.Struct(s).SetUint16(4, v)
}

// TokenizerInfo_List is a list of TokenizerInfo.
type TokenizerInfo_List = capnp.StructList[TokenizerInfo]

// NewTokenizerInfo creates a new list of TokenizerInfo.
func NewTokenizerInfo_List(s *capnp.Segment, sz int32) (TokenizerInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[TokenizerInfo](l), err
}

// TokenizerInfo_Future is a wrapper for a TokenizerInfo promised by a client call.
type TokenizerInfo_Future struct{ *capnp.Future }

func (f TokenizerInfo_Future) Struct() (TokenizerInfo, error) {
	p, err := f.Future.Ptr()
	return TokenizerInfo(p.Struct()), err
}
func (p TokenizerInfo_Future) Reserved2() *capnp.Future {
	return p.Future.Field(2, nil)
}

type ArchConfig capnp.Struct

// ArchConfig_TypeID is the unique identifier for the type ArchConfig.
const ArchConfig_TypeID = 0xa59716d6849bbf90

func NewArchConfig(s *capnp.Segment) (ArchConfig, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 6})
	return ArchConfig(st), err
}

func NewRootArchConfig(s *capnp.Segment) (ArchConfig, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 6})
	return ArchConfig(st), err
}

func ReadRootArchConfig(msg *capnp.Message) (ArchConfig, error) {
	root, err := msg.Root()
	return ArchConfig(root.Struct()), err
}

func (s ArchConfig) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ArchConfig) DecodeFromPtr(p capnp.Ptr) ArchConfig {
	return ArchConfig(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ArchConfig) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ArchConfig) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ArchConfig) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ArchConfig) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ArchConfig) Reserved0() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s ArchConfig) SetReserved0(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s ArchConfig) NLayers() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s ArchConfig) SetNLayers(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s ArchConfig) Reserved2() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s ArchConfig) SetReserved2(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s ArchConfig) Reserved3() uint32 {
	return capnp.Struct(s).Uint32(12)
}

func (s ArchConfig) SetReserved3(v uint32) {
	capnp.Struct(s).SetUint32(12, v)
}

func (s ArchConfig) Reserved4() uint32 {
	return capnp.Struct(s).Uint32(16)
}

func (s ArchConfig) SetReserved4(v uint32) {
	capnp.Struct(s).SetUint32(16, v)
}

func (s ArchConfig) Reserved5() uint32 {
	return capnp.Struct(s).Uint32(20)
}

func (s ArchConfig) SetReserved5(v uint32) {
	capnp.Struct(s).SetUint32(20, v)
}

func (s ArchConfig) VocabSize() uint32 {
	return capnp.Struct(s).Uint32(24)
}

func (s ArchConfig) SetVocabSize(v uint32) {
	capnp.Struct(s).SetUint32(24, v)
}

func (s ArchConfig) Reserved7() uint32 {
	return capnp.Struct(s).Uint32(28)
}

func (s ArchConfig) SetReserved7(v uint32) {
	capnp.Struct(s).SetUint32(28, v)
}

func (s ArchConfig) Reserved8() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(32))
}

func (s ArchConfig) SetReserved8(v float32) {
	capnp.Struct(s).SetUint32(32, math.Float32bits(v))
}

func (s ArchConfig) Reserved9() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(0)
}

func (s ArchConfig) HasReserved9() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ArchConfig) SetReserved9(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(0, v)
}
func (s ArchConfig) Swa() (SwaConfig, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return SwaConfig(p.Struct()), err
}

func (s ArchConfig) HasSwa() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ArchConfig) SetSwa(v SwaConfig) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewSwa sets the swa field to a newly
// allocated SwaConfig struct, preferring placement in s's segment.
func (s ArchConfig) NewSwa() (SwaConfig, error) {
	ss, err := NewSwaConfig(capnp.Struct(s).Segment())
	if err != nil {
		return SwaConfig{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ArchConfig) Reserved11() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(2)
}

func (s ArchConfig) HasReserved11() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ArchConfig) SetReserved11(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(2, v)
}
func (s ArchConfig) Reserved12() bool {
	return capnp.Struct(s).Bit(288)
}

func (s ArchConfig) SetReserved12(v bool) {
	capnp.Struct(s).SetBit(288, v)
}

func (s ArchConfig) Reserved13() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(3)
}

func (s ArchConfig) HasReserved13() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ArchConfig) SetReserved13(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(3, v)
}
func (s ArchConfig) Reserved14() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(4)
}

func (s ArchConfig) HasReserved14() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s ArchConfig) SetReserved14(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(4, v)
}
func (s ArchConfig) Reserved15() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(5)
}

func (s ArchConfig) HasReserved15() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s ArchConfig) SetReserved15(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(5, v)
}

// ArchConfig_List is a list of ArchConfig.
type ArchConfig_List = capnp.StructList[ArchConfig]

// NewArchConfig creates a new list of ArchConfig.
func NewArchConfig_List(s *capnp.Segment, sz int32) (ArchConfig_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 40, PointerCount: 6}, sz)
	return capnp.StructList[ArchConfig](l), err
}

// ArchConfig_Future is a wrapper for a ArchConfig promised by a client call.
type ArchConfig_Future struct{ *capnp.Future }

func (f ArchConfig_Future) Struct() (ArchConfig, error) {
	p, err := f.Future.Ptr()
	return ArchConfig(p.Struct()), err
}
func (p ArchConfig_Future) Reserved9() *capnp.Future {
	return p.Future.Field(0, nil)
}
func (p ArchConfig_Future) Swa() SwaConfig_Future {
	return SwaConfig_Future{Future: p.Future.Field(1, nil)}
}
func (p ArchConfig_Future) Reserved11() *capnp.Future {
	return p.Future.Field(2, nil)
}
func (p ArchConfig_Future) Reserved13() *capnp.Future {
	return p.Future.Field(3, nil)
}
func (p ArchConfig_Future) Reserved14() *capnp.Future {
	return p.Future.Field(4, nil)
}
func (p ArchConfig_Future) Reserved15() *capnp.Future {
	return p.Future.Field(5, nil)
}

type SwaConfig capnp.Struct

// SwaConfig_TypeID is the unique identifier for the type SwaConfig.
const SwaConfig_TypeID = 0xe67869945d5b5a16

func NewSwaConfig(s *capnp.Segment) (SwaConfig, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return SwaConfig(st), err
}

func NewRootSwaConfig(s *capnp.Segment) (SwaConfig, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return SwaConfig(st), err
}

func ReadRootSwaConfig(msg *capnp.Message) (SwaConfig, error) {
	root, err := msg.Root()
	return SwaConfig(root.Struct()), err
}

func (s SwaConfig) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SwaConfig) DecodeFromPtr(p capnp.Ptr) SwaConfig {
	return SwaConfig(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SwaConfig) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SwaConfig) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SwaConfig) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SwaConfig) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SwaConfig) MaxSeqLen() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s SwaConfig) SetMaxSeqLen(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s SwaConfig) Padding() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s SwaConfig) SetPadding(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s SwaConfig) NumUsers() (OptionalUInt32, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return OptionalUInt32(p.Struct()), err
}

func (s SwaConfig) HasNumUsers() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SwaConfig) SetNumUsers(v OptionalUInt32) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewNumUsers sets the numUsers field to a newly
// allocated OptionalUInt32 struct, preferring placement in s's segment.
func (s SwaConfig) NewNumUsers() (OptionalUInt32, error) {
	ss, err := NewOptionalUInt32(capnp.Struct(s).Segment())
	if err != nil {
		return OptionalUInt32{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// SwaConfig_List is a list of SwaConfig.
type SwaConfig_List = capnp.StructList[SwaConfig]

// NewSwaConfig creates a new list of SwaConfig.
func NewSwaConfig_List(s *capnp.Segment, sz int32) (SwaConfig_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[SwaConfig](l), err
}

// SwaConfig_Future is a wrapper for a SwaConfig promised by a client call.
type SwaConfig_Future struct{ *capnp.Future }

func (f SwaConfig_Future) Struct() (SwaConfig, error) {
	p, err := f.Future.Ptr()
	return SwaConfig(p.Struct()), err
}
func (p SwaConfig_Future) NumUsers() OptionalUInt32_Future {
	return OptionalUInt32_Future{Future: p.Future.Field(0, nil)}
}

type DeploymentInfo capnp.Struct

// DeploymentInfo_TypeID is the unique identifier for the type DeploymentInfo.
const DeploymentInfo_TypeID = 0xa151d4fb5c342435

func NewDeploymentInfo(s *capnp.Segment) (DeploymentInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return DeploymentInfo(st), err
}

func NewRootDeploymentInfo(s *capnp.Segment) (DeploymentInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return DeploymentInfo(st), err
}

func ReadRootDeploymentInfo(msg *capnp.Message) (DeploymentInfo, error) {
	root, err := msg.Root()
	return DeploymentInfo(root.Struct()), err
}

func (s DeploymentInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (DeploymentInfo) DecodeFromPtr(p capnp.Ptr) DeploymentInfo {
	return DeploymentInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s DeploymentInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s DeploymentInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s DeploymentInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s DeploymentInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s DeploymentInfo) CompilationMode() CompilationMode {
	return CompilationMode(capnp.Struct(s).Uint16(0))
}

func (s DeploymentInfo) SetCompilationMode(v CompilationMode) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s DeploymentInfo) NumLpuNodes() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s DeploymentInfo) SetNumLpuNodes(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s DeploymentInfo) Reserved2() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s DeploymentInfo) SetReserved2(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s DeploymentInfo) Program() (ProgramConfig, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ProgramConfig(p.Struct()), err
}

func (s DeploymentInfo) HasProgram() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s DeploymentInfo) SetProgram(v ProgramConfig) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewProgram sets the program field to a newly
// allocated ProgramConfig struct, preferring placement in s's segment.
func (s DeploymentInfo) NewProgram() (ProgramConfig, error) {
	ss, err := NewProgramConfig(capnp.Struct(s).Segment())
	if err != nil {
		return ProgramConfig{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s DeploymentInfo) SelectedPropSyncChains() (PropSyncChain_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return PropSyncChain_List(p.List()), err
}

func (s DeploymentInfo) HasSelectedPropSyncChains() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s DeploymentInfo) SetSelectedPropSyncChains(v PropSyncChain_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewSelectedPropSyncChains sets the selectedPropSyncChains field to a newly
// allocated PropSyncChain_List, preferring placement in s's segment.
func (s DeploymentInfo) NewSelectedPropSyncChains(n int32) (PropSyncChain_List, error) {
	l, err := NewPropSyncChain_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return PropSyncChain_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s DeploymentInfo) RuntimeIo() (RuntimeIoConfig, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return RuntimeIoConfig(p.Struct()), err
}

func (s DeploymentInfo) HasRuntimeIo() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s DeploymentInfo) SetRuntimeIo(v RuntimeIoConfig) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewRuntimeIo sets the runtimeIo field to a newly
// allocated RuntimeIoConfig struct, preferring placement in s's segment.
func (s DeploymentInfo) NewRuntimeIo() (RuntimeIoConfig, error) {
	ss, err := NewRuntimeIoConfig(capnp.Struct(s).Segment())
	if err != nil {
		return RuntimeIoConfig{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

// DeploymentInfo_List is a list of DeploymentInfo.
type DeploymentInfo_List = capnp.StructList[DeploymentInfo]

// NewDeploymentInfo creates a new list of DeploymentInfo.
func NewDeploymentInfo_List(s *capnp.Segment, sz int32) (DeploymentInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3}, sz)
	return capnp.StructList[DeploymentInfo](l), err
}

// DeploymentInfo_Future is a wrapper for a DeploymentInfo promised by a client call.
type DeploymentInfo_Future struct{ *capnp.Future }

func (f DeploymentInfo_Future) Struct() (DeploymentInfo, error) {
	p, err := f.Future.Ptr()
	return DeploymentInfo(p.Struct()), err
}
func (p DeploymentInfo_Future) Program() ProgramConfig_Future {
	return ProgramConfig_Future{Future: p.Future.Field(0, nil)}
}
func (p DeploymentInfo_Future) RuntimeIo() RuntimeIoConfig_Future {
	return RuntimeIoConfig_Future{Future: p.Future.Field(2, nil)}
}

type CompilationMode uint16

// CompilationMode_TypeID is the unique identifier for the type CompilationMode.
const CompilationMode_TypeID = 0xf66fba7eaeef9fd8

// Values of CompilationMode.
const (
	CompilationMode_lpuOnly CompilationMode = 0
	CompilationMode_lpx     CompilationMode = 1
)

// String returns the enum's constant name.
func (c CompilationMode) String() string {
	switch c {
	case CompilationMode_lpuOnly:
		return "lpuOnly"
	case CompilationMode_lpx:
		return "lpx"

	default:
		return ""
	}
}

// CompilationModeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func CompilationModeFromString(c string) CompilationMode {
	switch c {
	case "lpuOnly":
		return CompilationMode_lpuOnly
	case "lpx":
		return CompilationMode_lpx

	default:
		return 0
	}
}

type CompilationMode_List = capnp.EnumList[CompilationMode]

func NewCompilationMode_List(s *capnp.Segment, sz int32) (CompilationMode_List, error) {
	return capnp.NewEnumList[CompilationMode](s, sz)
}

type ProgramConfig capnp.Struct

// ProgramConfig_TypeID is the unique identifier for the type ProgramConfig.
const ProgramConfig_TypeID = 0xc22680a74d7bbfe2

func NewProgramConfig(s *capnp.Segment) (ProgramConfig, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 4})
	return ProgramConfig(st), err
}

func NewRootProgramConfig(s *capnp.Segment) (ProgramConfig, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 4})
	return ProgramConfig(st), err
}

func ReadRootProgramConfig(msg *capnp.Message) (ProgramConfig, error) {
	root, err := msg.Root()
	return ProgramConfig(root.Struct()), err
}

func (s ProgramConfig) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ProgramConfig) DecodeFromPtr(p capnp.Ptr) ProgramConfig {
	return ProgramConfig(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ProgramConfig) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ProgramConfig) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ProgramConfig) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ProgramConfig) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ProgramConfig) ProgramName() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ProgramConfig) HasProgramName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ProgramConfig) ProgramNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ProgramConfig) SetProgramName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ProgramConfig) PackageName() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ProgramConfig) HasPackageName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ProgramConfig) PackageNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ProgramConfig) SetPackageName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ProgramConfig) BatchSize() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s ProgramConfig) SetBatchSize(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s ProgramConfig) SequenceLength() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s ProgramConfig) SetSequenceLength(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s ProgramConfig) InputSize() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s ProgramConfig) SetInputSize(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s ProgramConfig) OutputSize() uint32 {
	return capnp.Struct(s).Uint32(12)
}

func (s ProgramConfig) SetOutputSize(v uint32) {
	capnp.Struct(s).SetUint32(12, v)
}

func (s ProgramConfig) Dkvc() (DkvcConfig, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return DkvcConfig(p.Struct()), err
}

func (s ProgramConfig) HasDkvc() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ProgramConfig) SetDkvc(v DkvcConfig) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewDkvc sets the dkvc field to a newly
// allocated DkvcConfig struct, preferring placement in s's segment.
func (s ProgramConfig) NewDkvc() (DkvcConfig, error) {
	ss, err := NewDkvcConfig(capnp.Struct(s).Segment())
	if err != nil {
		return DkvcConfig{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ProgramConfig) NumKvCaches() uint32 {
	return capnp.Struct(s).Uint32(16)
}

func (s ProgramConfig) SetNumKvCaches(v uint32) {
	capnp.Struct(s).SetUint32(16, v)
}

func (s ProgramConfig) NumBatchSplitDivisions() uint32 {
	return capnp.Struct(s).Uint32(20)
}

func (s ProgramConfig) SetNumBatchSplitDivisions(v uint32) {
	capnp.Struct(s).SetUint32(20, v)
}

func (s ProgramConfig) BatchFolding() bool {
	return capnp.Struct(s).Bit(192)
}

func (s ProgramConfig) SetBatchFolding(v bool) {
	capnp.Struct(s).SetBit(192, v)
}

func (s ProgramConfig) SupportsCpuEmbeddings() bool {
	return capnp.Struct(s).Bit(193)
}

func (s ProgramConfig) SetSupportsCpuEmbeddings(v bool) {
	capnp.Struct(s).SetBit(193, v)
}

func (s ProgramConfig) Reserved11() bool {
	return capnp.Struct(s).Bit(194)
}

func (s ProgramConfig) SetReserved11(v bool) {
	capnp.Struct(s).SetBit(194, v)
}

func (s ProgramConfig) StandaloneTokenEmbeddings() bool {
	return capnp.Struct(s).Bit(195)
}

func (s ProgramConfig) SetStandaloneTokenEmbeddings(v bool) {
	capnp.Struct(s).SetBit(195, v)
}

func (s ProgramConfig) Topk() (OptionalUInt32, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return OptionalUInt32(p.Struct()), err
}

func (s ProgramConfig) HasTopk() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ProgramConfig) SetTopk(v OptionalUInt32) error {
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewTopk sets the topk field to a newly
// allocated OptionalUInt32 struct, preferring placement in s's segment.
func (s ProgramConfig) NewTopk() (OptionalUInt32, error) {
	ss, err := NewOptionalUInt32(capnp.Struct(s).Segment())
	if err != nil {
		return OptionalUInt32{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ProgramConfig) EnableLogitMasking() bool {
	return capnp.Struct(s).Bit(196)
}

func (s ProgramConfig) SetEnableLogitMasking(v bool) {
	capnp.Struct(s).SetBit(196, v)
}

func (s ProgramConfig) SwaChunked() bool {
	return capnp.Struct(s).Bit(197)
}

func (s ProgramConfig) SetSwaChunked(v bool) {
	capnp.Struct(s).SetBit(197, v)
}

func (s ProgramConfig) NumSwaDkvcBlocks() uint32 {
	return capnp.Struct(s).Uint32(28)
}

func (s ProgramConfig) SetNumSwaDkvcBlocks(v uint32) {
	capnp.Struct(s).SetUint32(28, v)
}

// ProgramConfig_List is a list of ProgramConfig.
type ProgramConfig_List = capnp.StructList[ProgramConfig]

// NewProgramConfig creates a new list of ProgramConfig.
func NewProgramConfig_List(s *capnp.Segment, sz int32) (ProgramConfig_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 4}, sz)
	return capnp.StructList[ProgramConfig](l), err
}

// ProgramConfig_Future is a wrapper for a ProgramConfig promised by a client call.
type ProgramConfig_Future struct{ *capnp.Future }

func (f ProgramConfig_Future) Struct() (ProgramConfig, error) {
	p, err := f.Future.Ptr()
	return ProgramConfig(p.Struct()), err
}
func (p ProgramConfig_Future) Dkvc() DkvcConfig_Future {
	return DkvcConfig_Future{Future: p.Future.Field(2, nil)}
}
func (p ProgramConfig_Future) Topk() OptionalUInt32_Future {
	return OptionalUInt32_Future{Future: p.Future.Field(3, nil)}
}

type DkvcConfig capnp.Struct

// DkvcConfig_TypeID is the unique identifier for the type DkvcConfig.
const DkvcConfig_TypeID = 0xf04def427d04d873

func NewDkvcConfig(s *capnp.Segment) (DkvcConfig, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return DkvcConfig(st), err
}

func NewRootDkvcConfig(s *capnp.Segment) (DkvcConfig, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return DkvcConfig(st), err
}

func ReadRootDkvcConfig(msg *capnp.Message) (DkvcConfig, error) {
	root, err := msg.Root()
	return DkvcConfig(root.Struct()), err
}

func (s DkvcConfig) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (DkvcConfig) DecodeFromPtr(p capnp.Ptr) DkvcConfig {
	return DkvcConfig(capnp.Struct{}.DecodeFromPtr(p))
}

func (s DkvcConfig) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s DkvcConfig) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s DkvcConfig) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s DkvcConfig) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s DkvcConfig) NumBlocksPerKvCache() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s DkvcConfig) SetNumBlocksPerKvCache(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

// DkvcConfig_List is a list of DkvcConfig.
type DkvcConfig_List = capnp.StructList[DkvcConfig]

// NewDkvcConfig creates a new list of DkvcConfig.
func NewDkvcConfig_List(s *capnp.Segment, sz int32) (DkvcConfig_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[DkvcConfig](l), err
}

// DkvcConfig_Future is a wrapper for a DkvcConfig promised by a client call.
type DkvcConfig_Future struct{ *capnp.Future }

func (f DkvcConfig_Future) Struct() (DkvcConfig, error) {
	p, err := f.Future.Ptr()
	return DkvcConfig(p.Struct()), err
}

type PropSyncChain capnp.Struct

// PropSyncChain_TypeID is the unique identifier for the type PropSyncChain.
const PropSyncChain_TypeID = 0xe4a2574339b7691f

func NewPropSyncChain(s *capnp.Segment) (PropSyncChain, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return PropSyncChain(st), err
}

func NewRootPropSyncChain(s *capnp.Segment) (PropSyncChain, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return PropSyncChain(st), err
}

func ReadRootPropSyncChain(msg *capnp.Message) (PropSyncChain, error) {
	root, err := msg.Root()
	return PropSyncChain(root.Struct()), err
}

func (s PropSyncChain) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PropSyncChain) DecodeFromPtr(p capnp.Ptr) PropSyncChain {
	return PropSyncChain(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PropSyncChain) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PropSyncChain) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PropSyncChain) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PropSyncChain) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PropSyncChain) PartitionIds() (capnp.UInt32List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.UInt32List(p.List()), err
}

func (s PropSyncChain) HasPartitionIds() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PropSyncChain) SetPartitionIds(v capnp.UInt32List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewPartitionIds sets the partitionIds field to a newly
// allocated capnp.UInt32List, preferring placement in s's segment.
func (s PropSyncChain) NewPartitionIds(n int32) (capnp.UInt32List, error) {
	l, err := capnp.NewUInt32List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt32List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// PropSyncChain_List is a list of PropSyncChain.
type PropSyncChain_List = capnp.StructList[PropSyncChain]

// NewPropSyncChain creates a new list of PropSyncChain.
func NewPropSyncChain_List(s *capnp.Segment, sz int32) (PropSyncChain_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[PropSyncChain](l), err
}

// PropSyncChain_Future is a wrapper for a PropSyncChain promised by a client call.
type PropSyncChain_Future struct{ *capnp.Future }

func (f PropSyncChain_Future) Struct() (PropSyncChain, error) {
	p, err := f.Future.Ptr()
	return PropSyncChain(p.Struct()), err
}

type RuntimeIoConfig capnp.Struct

// RuntimeIoConfig_TypeID is the unique identifier for the type RuntimeIoConfig.
const RuntimeIoConfig_TypeID = 0xd56d56fafa085238

func NewRuntimeIoConfig(s *capnp.Segment) (RuntimeIoConfig, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return RuntimeIoConfig(st), err
}

func NewRootRuntimeIoConfig(s *capnp.Segment) (RuntimeIoConfig, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return RuntimeIoConfig(st), err
}

func ReadRootRuntimeIoConfig(msg *capnp.Message) (RuntimeIoConfig, error) {
	root, err := msg.Root()
	return RuntimeIoConfig(root.Struct()), err
}

func (s RuntimeIoConfig) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RuntimeIoConfig) DecodeFromPtr(p capnp.Ptr) RuntimeIoConfig {
	return RuntimeIoConfig(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RuntimeIoConfig) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RuntimeIoConfig) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RuntimeIoConfig) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RuntimeIoConfig) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RuntimeIoConfig) Protocol() uint16 {
	return capnp.Struct(s).Uint16(0)
}

func (s RuntimeIoConfig) SetProtocol(v uint16) {
	capnp.Struct(s).SetUint16(0, v)
}

func (s RuntimeIoConfig) Reserved1() uint16 {
	return capnp.Struct(s).Uint16(2)
}

func (s RuntimeIoConfig) SetReserved1(v uint16) {
	capnp.Struct(s).SetUint16(2, v)
}

func (s RuntimeIoConfig) IoFpgaCount() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s RuntimeIoConfig) SetIoFpgaCount(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s RuntimeIoConfig) FanoutFactor() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s RuntimeIoConfig) SetFanoutFactor(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

// RuntimeIoConfig_List is a list of RuntimeIoConfig.
type RuntimeIoConfig_List = capnp.StructList[RuntimeIoConfig]

// NewRuntimeIoConfig creates a new list of RuntimeIoConfig.
func NewRuntimeIoConfig_List(s *capnp.Segment, sz int32) (RuntimeIoConfig_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[RuntimeIoConfig](l), err
}

// RuntimeIoConfig_Future is a wrapper for a RuntimeIoConfig promised by a client call.
type RuntimeIoConfig_Future struct{ *capnp.Future }

func (f RuntimeIoConfig_Future) Struct() (RuntimeIoConfig, error) {
	p, err := f.Future.Ptr()
	return RuntimeIoConfig(p.Struct()), err
}

type ArtifactInfo capnp.Struct

// ArtifactInfo_TypeID is the unique identifier for the type ArtifactInfo.
const ArtifactInfo_TypeID = 0xfd4e240e22cb8a78

func NewArtifactInfo(s *capnp.Segment) (ArtifactInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 7})
	return ArtifactInfo(st), err
}

func NewRootArtifactInfo(s *capnp.Segment) (ArtifactInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 7})
	return ArtifactInfo(st), err
}

func ReadRootArtifactInfo(msg *capnp.Message) (ArtifactInfo, error) {
	root, err := msg.Root()
	return ArtifactInfo(root.Struct()), err
}

func (s ArtifactInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ArtifactInfo) DecodeFromPtr(p capnp.Ptr) ArtifactInfo {
	return ArtifactInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ArtifactInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ArtifactInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ArtifactInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ArtifactInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ArtifactInfo) Partitions() (PartitionInfo_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return PartitionInfo_List(p.List()), err
}

func (s ArtifactInfo) HasPartitions() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ArtifactInfo) SetPartitions(v PartitionInfo_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewPartitions sets the partitions field to a newly
// allocated PartitionInfo_List, preferring placement in s's segment.
func (s ArtifactInfo) NewPartitions(n int32) (PartitionInfo_List, error) {
	l, err := NewPartitionInfo_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return PartitionInfo_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s ArtifactInfo) Reserved1() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(1)
}

func (s ArtifactInfo) HasReserved1() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ArtifactInfo) SetReserved1(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(1, v)
}
func (s ArtifactInfo) Reserved2() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(2)
}

func (s ArtifactInfo) HasReserved2() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ArtifactInfo) SetReserved2(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(2, v)
}
func (s ArtifactInfo) Reserved3() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(3)
}

func (s ArtifactInfo) HasReserved3() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ArtifactInfo) SetReserved3(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(3, v)
}
func (s ArtifactInfo) RuntimeAssets() (RuntimeAssets, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return RuntimeAssets(p.Struct()), err
}

func (s ArtifactInfo) HasRuntimeAssets() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s ArtifactInfo) SetRuntimeAssets(v RuntimeAssets) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewRuntimeAssets sets the runtimeAssets field to a newly
// allocated RuntimeAssets struct, preferring placement in s's segment.
func (s ArtifactInfo) NewRuntimeAssets() (RuntimeAssets, error) {
	ss, err := NewRuntimeAssets(capnp.Struct(s).Segment())
	if err != nil {
		return RuntimeAssets{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ArtifactInfo) PartSelect() (PartSelect, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return PartSelect(p.Struct()), err
}

func (s ArtifactInfo) HasPartSelect() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s ArtifactInfo) SetPartSelect(v PartSelect) error {
	return capnp.Struct(s).SetPtr(5, capnp.Struct(v).ToPtr())
}

// NewPartSelect sets the partSelect field to a newly
// allocated PartSelect struct, preferring placement in s's segment.
func (s ArtifactInfo) NewPartSelect() (PartSelect, error) {
	ss, err := NewPartSelect(capnp.Struct(s).Segment())
	if err != nil {
		return PartSelect{}, err
	}
	err = capnp.Struct(s).SetPtr(5, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ArtifactInfo) Reserved6() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(6)
}

func (s ArtifactInfo) HasReserved6() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s ArtifactInfo) SetReserved6(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(6, v)
}

// ArtifactInfo_List is a list of ArtifactInfo.
type ArtifactInfo_List = capnp.StructList[ArtifactInfo]

// NewArtifactInfo creates a new list of ArtifactInfo.
func NewArtifactInfo_List(s *capnp.Segment, sz int32) (ArtifactInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 7}, sz)
	return capnp.StructList[ArtifactInfo](l), err
}

// ArtifactInfo_Future is a wrapper for a ArtifactInfo promised by a client call.
type ArtifactInfo_Future struct{ *capnp.Future }

func (f ArtifactInfo_Future) Struct() (ArtifactInfo, error) {
	p, err := f.Future.Ptr()
	return ArtifactInfo(p.Struct()), err
}
func (p ArtifactInfo_Future) Reserved1() *capnp.Future {
	return p.Future.Field(1, nil)
}
func (p ArtifactInfo_Future) Reserved2() *capnp.Future {
	return p.Future.Field(2, nil)
}
func (p ArtifactInfo_Future) Reserved3() *capnp.Future {
	return p.Future.Field(3, nil)
}
func (p ArtifactInfo_Future) RuntimeAssets() RuntimeAssets_Future {
	return RuntimeAssets_Future{Future: p.Future.Field(4, nil)}
}
func (p ArtifactInfo_Future) PartSelect() PartSelect_Future {
	return PartSelect_Future{Future: p.Future.Field(5, nil)}
}
func (p ArtifactInfo_Future) Reserved6() *capnp.Future {
	return p.Future.Field(6, nil)
}

type RuntimeAssets capnp.Struct

// RuntimeAssets_TypeID is the unique identifier for the type RuntimeAssets.
const RuntimeAssets_TypeID = 0xd7d44733b7c9406d

func NewRuntimeAssets(s *capnp.Segment) (RuntimeAssets, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return RuntimeAssets(st), err
}

func NewRootRuntimeAssets(s *capnp.Segment) (RuntimeAssets, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return RuntimeAssets(st), err
}

func ReadRootRuntimeAssets(msg *capnp.Message) (RuntimeAssets, error) {
	root, err := msg.Root()
	return RuntimeAssets(root.Struct()), err
}

func (s RuntimeAssets) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RuntimeAssets) DecodeFromPtr(p capnp.Ptr) RuntimeAssets {
	return RuntimeAssets(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RuntimeAssets) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RuntimeAssets) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RuntimeAssets) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RuntimeAssets) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RuntimeAssets) TokenEmbeddingsPath() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s RuntimeAssets) HasTokenEmbeddingsPath() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RuntimeAssets) TokenEmbeddingsPathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s RuntimeAssets) SetTokenEmbeddingsPath(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s RuntimeAssets) Reserved1() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(1)
}

func (s RuntimeAssets) HasReserved1() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s RuntimeAssets) SetReserved1(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(1, v)
}

// RuntimeAssets_List is a list of RuntimeAssets.
type RuntimeAssets_List = capnp.StructList[RuntimeAssets]

// NewRuntimeAssets creates a new list of RuntimeAssets.
func NewRuntimeAssets_List(s *capnp.Segment, sz int32) (RuntimeAssets_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[RuntimeAssets](l), err
}

// RuntimeAssets_Future is a wrapper for a RuntimeAssets promised by a client call.
type RuntimeAssets_Future struct{ *capnp.Future }

func (f RuntimeAssets_Future) Struct() (RuntimeAssets, error) {
	p, err := f.Future.Ptr()
	return RuntimeAssets(p.Struct()), err
}
func (p RuntimeAssets_Future) Reserved1() *capnp.Future {
	return p.Future.Field(1, nil)
}

type PartitionInfo capnp.Struct
type PartitionInfo_detail PartitionInfo
type PartitionInfo_detail_Which uint16

const (
	PartitionInfo_detail_Which_lpu  PartitionInfo_detail_Which = 0
	PartitionInfo_detail_Which_cuda PartitionInfo_detail_Which = 1
	PartitionInfo_detail_Which_cpu  PartitionInfo_detail_Which = 2
)

func (w PartitionInfo_detail_Which) String() string {
	const s = "lpucudacpu"
	switch w {
	case PartitionInfo_detail_Which_lpu:
		return s[0:3]
	case PartitionInfo_detail_Which_cuda:
		return s[3:7]
	case PartitionInfo_detail_Which_cpu:
		return s[7:10]

	}
	return "PartitionInfo_detail_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// PartitionInfo_TypeID is the unique identifier for the type PartitionInfo.
const PartitionInfo_TypeID = 0xc2825cc7c53e1399

func NewPartitionInfo(s *capnp.Segment) (PartitionInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return PartitionInfo(st), err
}

func NewRootPartitionInfo(s *capnp.Segment) (PartitionInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return PartitionInfo(st), err
}

func ReadRootPartitionInfo(msg *capnp.Message) (PartitionInfo, error) {
	root, err := msg.Root()
	return PartitionInfo(root.Struct()), err
}

func (s PartitionInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PartitionInfo) DecodeFromPtr(p capnp.Ptr) PartitionInfo {
	return PartitionInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PartitionInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PartitionInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PartitionInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PartitionInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PartitionInfo) Partition() (PartitionRef, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return PartitionRef(p.Struct()), err
}

func (s PartitionInfo) HasPartition() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PartitionInfo) SetPartition(v PartitionRef) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewPartition sets the partition field to a newly
// allocated PartitionRef struct, preferring placement in s's segment.
func (s PartitionInfo) NewPartition() (PartitionRef, error) {
	ss, err := NewPartitionRef(capnp.Struct(s).Segment())
	if err != nil {
		return PartitionRef{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s PartitionInfo) Reserved1() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(1)
}

func (s PartitionInfo) HasReserved1() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s PartitionInfo) SetReserved1(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(1, v)
}
func (s PartitionInfo) Reserved2() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(2)
}

func (s PartitionInfo) HasReserved2() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s PartitionInfo) SetReserved2(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(2, v)
}
func (s PartitionInfo) Detail() PartitionInfo_detail { return PartitionInfo_detail(s) }

func (s PartitionInfo_detail) Which() PartitionInfo_detail_Which {
	return PartitionInfo_detail_Which(capnp.Struct(s).Uint16(0))
}
func (s PartitionInfo_detail) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PartitionInfo_detail) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PartitionInfo_detail) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PartitionInfo_detail) Lpu() (LpuPartitionArtifact, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != lpu")
	}
	p, err := capnp.Struct(s).Ptr(3)
	return LpuPartitionArtifact(p.Struct()), err
}

func (s PartitionInfo_detail) HasLpu() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(3)
}

func (s PartitionInfo_detail) SetLpu(v LpuPartitionArtifact) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewLpu sets the lpu field to a newly
// allocated LpuPartitionArtifact struct, preferring placement in s's segment.
func (s PartitionInfo_detail) NewLpu() (LpuPartitionArtifact, error) {
	capnp.Struct(s).SetUint16(0, 0)
	ss, err := NewLpuPartitionArtifact(capnp.Struct(s).Segment())
	if err != nil {
		return LpuPartitionArtifact{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s PartitionInfo_detail) Cuda() (CudaPartitionArtifact, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != cuda")
	}
	p, err := capnp.Struct(s).Ptr(3)
	return CudaPartitionArtifact(p.Struct()), err
}

func (s PartitionInfo_detail) HasCuda() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(3)
}

func (s PartitionInfo_detail) SetCuda(v CudaPartitionArtifact) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewCuda sets the cuda field to a newly
// allocated CudaPartitionArtifact struct, preferring placement in s's segment.
func (s PartitionInfo_detail) NewCuda() (CudaPartitionArtifact, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewCudaPartitionArtifact(capnp.Struct(s).Segment())
	if err != nil {
		return CudaPartitionArtifact{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s PartitionInfo_detail) Cpu() (CpuPartitionArtifact, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != cpu")
	}
	p, err := capnp.Struct(s).Ptr(3)
	return CpuPartitionArtifact(p.Struct()), err
}

func (s PartitionInfo_detail) HasCpu() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(3)
}

func (s PartitionInfo_detail) SetCpu(v CpuPartitionArtifact) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewCpu sets the cpu field to a newly
// allocated CpuPartitionArtifact struct, preferring placement in s's segment.
func (s PartitionInfo_detail) NewCpu() (CpuPartitionArtifact, error) {
	capnp.Struct(s).SetUint16(0, 2)
	ss, err := NewCpuPartitionArtifact(capnp.Struct(s).Segment())
	if err != nil {
		return CpuPartitionArtifact{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

// PartitionInfo_List is a list of PartitionInfo.
type PartitionInfo_List = capnp.StructList[PartitionInfo]

// NewPartitionInfo creates a new list of PartitionInfo.
func NewPartitionInfo_List(s *capnp.Segment, sz int32) (PartitionInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[PartitionInfo](l), err
}

// PartitionInfo_Future is a wrapper for a PartitionInfo promised by a client call.
type PartitionInfo_Future struct{ *capnp.Future }

func (f PartitionInfo_Future) Struct() (PartitionInfo, error) {
	p, err := f.Future.Ptr()
	return PartitionInfo(p.Struct()), err
}
func (p PartitionInfo_Future) Partition() PartitionRef_Future {
	return PartitionRef_Future{Future: p.Future.Field(0, nil)}
}
func (p PartitionInfo_Future) Reserved1() *capnp.Future {
	return p.Future.Field(1, nil)
}
func (p PartitionInfo_Future) Reserved2() *capnp.Future {
	return p.Future.Field(2, nil)
}
func (p PartitionInfo_Future) Detail() PartitionInfo_detail_Future {
	return PartitionInfo_detail_Future{p.Future}
}

// PartitionInfo_detail_Future is a wrapper for a PartitionInfo_detail promised by a client call.
type PartitionInfo_detail_Future struct{ *capnp.Future }

func (f PartitionInfo_detail_Future) Struct() (PartitionInfo_detail, error) {
	p, err := f.Future.Ptr()
	return PartitionInfo_detail(p.Struct()), err
}
func (p PartitionInfo_detail_Future) Lpu() LpuPartitionArtifact_Future {
	return LpuPartitionArtifact_Future{Future: p.Future.Field(3, nil)}
}
func (p PartitionInfo_detail_Future) Cuda() CudaPartitionArtifact_Future {
	return CudaPartitionArtifact_Future{Future: p.Future.Field(3, nil)}
}
func (p PartitionInfo_detail_Future) Cpu() CpuPartitionArtifact_Future {
	return CpuPartitionArtifact_Future{Future: p.Future.Field(3, nil)}
}

type PartitionRef capnp.Struct

// PartitionRef_TypeID is the unique identifier for the type PartitionRef.
const PartitionRef_TypeID = 0xcc1f6d5da735cb49

func NewPartitionRef(s *capnp.Segment) (PartitionRef, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return PartitionRef(st), err
}

func NewRootPartitionRef(s *capnp.Segment) (PartitionRef, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return PartitionRef(st), err
}

func ReadRootPartitionRef(msg *capnp.Message) (PartitionRef, error) {
	root, err := msg.Root()
	return PartitionRef(root.Struct()), err
}

func (s PartitionRef) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PartitionRef) DecodeFromPtr(p capnp.Ptr) PartitionRef {
	return PartitionRef(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PartitionRef) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PartitionRef) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PartitionRef) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PartitionRef) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PartitionRef) DeviceType() DeviceType {
	return DeviceType(capnp.Struct(s).Uint16(0))
}

func (s PartitionRef) SetDeviceType(v DeviceType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s PartitionRef) PartitionId() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s PartitionRef) SetPartitionId(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

// PartitionRef_List is a list of PartitionRef.
type PartitionRef_List = capnp.StructList[PartitionRef]

// NewPartitionRef creates a new list of PartitionRef.
func NewPartitionRef_List(s *capnp.Segment, sz int32) (PartitionRef_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[PartitionRef](l), err
}

// PartitionRef_Future is a wrapper for a PartitionRef promised by a client call.
type PartitionRef_Future struct{ *capnp.Future }

func (f PartitionRef_Future) Struct() (PartitionRef, error) {
	p, err := f.Future.Ptr()
	return PartitionRef(p.Struct()), err
}

type LpuPartitionArtifact capnp.Struct

// LpuPartitionArtifact_TypeID is the unique identifier for the type LpuPartitionArtifact.
const LpuPartitionArtifact_TypeID = 0xae800a9bf3fc6050

func NewLpuPartitionArtifact(s *capnp.Segment) (LpuPartitionArtifact, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return LpuPartitionArtifact(st), err
}

func NewRootLpuPartitionArtifact(s *capnp.Segment) (LpuPartitionArtifact, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return LpuPartitionArtifact(st), err
}

func ReadRootLpuPartitionArtifact(msg *capnp.Message) (LpuPartitionArtifact, error) {
	root, err := msg.Root()
	return LpuPartitionArtifact(root.Struct()), err
}

func (s LpuPartitionArtifact) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (LpuPartitionArtifact) DecodeFromPtr(p capnp.Ptr) LpuPartitionArtifact {
	return LpuPartitionArtifact(capnp.Struct{}.DecodeFromPtr(p))
}

func (s LpuPartitionArtifact) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s LpuPartitionArtifact) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s LpuPartitionArtifact) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s LpuPartitionArtifact) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s LpuPartitionArtifact) Path() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s LpuPartitionArtifact) HasPath() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s LpuPartitionArtifact) PathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s LpuPartitionArtifact) SetPath(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s LpuPartitionArtifact) Topology() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s LpuPartitionArtifact) HasTopology() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s LpuPartitionArtifact) TopologyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s LpuPartitionArtifact) SetTopology(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s LpuPartitionArtifact) NumChips() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s LpuPartitionArtifact) SetNumChips(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s LpuPartitionArtifact) TopologyMetadata() (TopologyMetadata, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return TopologyMetadata(p.Struct()), err
}

func (s LpuPartitionArtifact) HasTopologyMetadata() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s LpuPartitionArtifact) SetTopologyMetadata(v TopologyMetadata) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewTopologyMetadata sets the topologyMetadata field to a newly
// allocated TopologyMetadata struct, preferring placement in s's segment.
func (s LpuPartitionArtifact) NewTopologyMetadata() (TopologyMetadata, error) {
	ss, err := NewTopologyMetadata(capnp.Struct(s).Segment())
	if err != nil {
		return TopologyMetadata{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s LpuPartitionArtifact) Reserved4() (capnp.Ptr, error) {
	return capnp.Struct(s).Ptr(3)
}

func (s LpuPartitionArtifact) HasReserved4() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s LpuPartitionArtifact) SetReserved4(v capnp.Ptr) error {
	return capnp.Struct(s).SetPtr(3, v)
}
func (s LpuPartitionArtifact) DevicesPerNode() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s LpuPartitionArtifact) SetDevicesPerNode(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

// LpuPartitionArtifact_List is a list of LpuPartitionArtifact.
type LpuPartitionArtifact_List = capnp.StructList[LpuPartitionArtifact]

// NewLpuPartitionArtifact creates a new list of LpuPartitionArtifact.
func NewLpuPartitionArtifact_List(s *capnp.Segment, sz int32) (LpuPartitionArtifact_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[LpuPartitionArtifact](l), err
}

// LpuPartitionArtifact_Future is a wrapper for a LpuPartitionArtifact promised by a client call.
type LpuPartitionArtifact_Future struct{ *capnp.Future }

func (f LpuPartitionArtifact_Future) Struct() (LpuPartitionArtifact, error) {
	p, err := f.Future.Ptr()
	return LpuPartitionArtifact(p.Struct()), err
}
func (p LpuPartitionArtifact_Future) TopologyMetadata() TopologyMetadata_Future {
	return TopologyMetadata_Future{Future: p.Future.Field(2, nil)}
}
func (p LpuPartitionArtifact_Future) Reserved4() *capnp.Future {
	return p.Future.Field(3, nil)
}

type CudaPartitionArtifact capnp.Struct

// CudaPartitionArtifact_TypeID is the unique identifier for the type CudaPartitionArtifact.
const CudaPartitionArtifact_TypeID = 0x9eaa468d1b6452a4

func NewCudaPartitionArtifact(s *capnp.Segment) (CudaPartitionArtifact, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CudaPartitionArtifact(st), err
}

func NewRootCudaPartitionArtifact(s *capnp.Segment) (CudaPartitionArtifact, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CudaPartitionArtifact(st), err
}

func ReadRootCudaPartitionArtifact(msg *capnp.Message) (CudaPartitionArtifact, error) {
	root, err := msg.Root()
	return CudaPartitionArtifact(root.Struct()), err
}

func (s CudaPartitionArtifact) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CudaPartitionArtifact) DecodeFromPtr(p capnp.Ptr) CudaPartitionArtifact {
	return CudaPartitionArtifact(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CudaPartitionArtifact) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CudaPartitionArtifact) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CudaPartitionArtifact) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CudaPartitionArtifact) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CudaPartitionArtifact_List is a list of CudaPartitionArtifact.
type CudaPartitionArtifact_List = capnp.StructList[CudaPartitionArtifact]

// NewCudaPartitionArtifact creates a new list of CudaPartitionArtifact.
func NewCudaPartitionArtifact_List(s *capnp.Segment, sz int32) (CudaPartitionArtifact_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CudaPartitionArtifact](l), err
}

// CudaPartitionArtifact_Future is a wrapper for a CudaPartitionArtifact promised by a client call.
type CudaPartitionArtifact_Future struct{ *capnp.Future }

func (f CudaPartitionArtifact_Future) Struct() (CudaPartitionArtifact, error) {
	p, err := f.Future.Ptr()
	return CudaPartitionArtifact(p.Struct()), err
}

type CpuPartitionArtifact capnp.Struct

// CpuPartitionArtifact_TypeID is the unique identifier for the type CpuPartitionArtifact.
const CpuPartitionArtifact_TypeID = 0x9c491b4f77040820

func NewCpuPartitionArtifact(s *capnp.Segment) (CpuPartitionArtifact, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CpuPartitionArtifact(st), err
}

func NewRootCpuPartitionArtifact(s *capnp.Segment) (CpuPartitionArtifact, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CpuPartitionArtifact(st), err
}

func ReadRootCpuPartitionArtifact(msg *capnp.Message) (CpuPartitionArtifact, error) {
	root, err := msg.Root()
	return CpuPartitionArtifact(root.Struct()), err
}

func (s CpuPartitionArtifact) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CpuPartitionArtifact) DecodeFromPtr(p capnp.Ptr) CpuPartitionArtifact {
	return CpuPartitionArtifact(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CpuPartitionArtifact) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CpuPartitionArtifact) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CpuPartitionArtifact) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CpuPartitionArtifact) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CpuPartitionArtifact_List is a list of CpuPartitionArtifact.
type CpuPartitionArtifact_List = capnp.StructList[CpuPartitionArtifact]

// NewCpuPartitionArtifact creates a new list of CpuPartitionArtifact.
func NewCpuPartitionArtifact_List(s *capnp.Segment, sz int32) (CpuPartitionArtifact_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CpuPartitionArtifact](l), err
}

// CpuPartitionArtifact_Future is a wrapper for a CpuPartitionArtifact promised by a client call.
type CpuPartitionArtifact_Future struct{ *capnp.Future }

func (f CpuPartitionArtifact_Future) Struct() (CpuPartitionArtifact, error) {
	p, err := f.Future.Ptr()
	return CpuPartitionArtifact(p.Struct()), err
}

type PartSelect capnp.Struct

// PartSelect_TypeID is the unique identifier for the type PartSelect.
const PartSelect_TypeID = 0x906961f37780d08b

func NewPartSelect(s *capnp.Segment) (PartSelect, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return PartSelect(st), err
}

func NewRootPartSelect(s *capnp.Segment) (PartSelect, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return PartSelect(st), err
}

func ReadRootPartSelect(msg *capnp.Message) (PartSelect, error) {
	root, err := msg.Root()
	return PartSelect(root.Struct()), err
}

func (s PartSelect) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PartSelect) DecodeFromPtr(p capnp.Ptr) PartSelect {
	return PartSelect(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PartSelect) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PartSelect) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PartSelect) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PartSelect) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PartSelect) Partitions() (PartitionRef_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return PartitionRef_List(p.List()), err
}

func (s PartSelect) HasPartitions() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PartSelect) SetPartitions(v PartitionRef_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewPartitions sets the partitions field to a newly
// allocated PartitionRef_List, preferring placement in s's segment.
func (s PartSelect) NewPartitions(n int32) (PartitionRef_List, error) {
	l, err := NewPartitionRef_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return PartitionRef_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// PartSelect_List is a list of PartSelect.
type PartSelect_List = capnp.StructList[PartSelect]

// NewPartSelect creates a new list of PartSelect.
func NewPartSelect_List(s *capnp.Segment, sz int32) (PartSelect_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[PartSelect](l), err
}

// PartSelect_Future is a wrapper for a PartSelect promised by a client call.
type PartSelect_Future struct{ *capnp.Future }

func (f PartSelect_Future) Struct() (PartSelect, error) {
	p, err := f.Future.Ptr()
	return PartSelect(p.Struct()), err
}

type DeviceType uint16

// DeviceType_TypeID is the unique identifier for the type DeviceType.
const DeviceType_TypeID = 0x9e4e2af44ac2e94e

// Values of DeviceType.
const (
	DeviceType_lpu  DeviceType = 0
	DeviceType_cuda DeviceType = 1
	DeviceType_cpu  DeviceType = 2
)

// String returns the enum's constant name.
func (c DeviceType) String() string {
	switch c {
	case DeviceType_lpu:
		return "lpu"
	case DeviceType_cuda:
		return "cuda"
	case DeviceType_cpu:
		return "cpu"

	default:
		return ""
	}
}

// DeviceTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func DeviceTypeFromString(c string) DeviceType {
	switch c {
	case "lpu":
		return DeviceType_lpu
	case "cuda":
		return DeviceType_cuda
	case "cpu":
		return DeviceType_cpu

	default:
		return 0
	}
}

type DeviceType_List = capnp.EnumList[DeviceType]

func NewDeviceType_List(s *capnp.Segment, sz int32) (DeviceType_List, error) {
	return capnp.NewEnumList[DeviceType](s, sz)
}

type TopologyMetadata capnp.Struct

// TopologyMetadata_TypeID is the unique identifier for the type TopologyMetadata.
const TopologyMetadata_TypeID = 0x9ac600e40b2f2bd2

func NewTopologyMetadata(s *capnp.Segment) (TopologyMetadata, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return TopologyMetadata(st), err
}

func NewRootTopologyMetadata(s *capnp.Segment) (TopologyMetadata, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return TopologyMetadata(st), err
}

func ReadRootTopologyMetadata(msg *capnp.Message) (TopologyMetadata, error) {
	root, err := msg.Root()
	return TopologyMetadata(root.Struct()), err
}

func (s TopologyMetadata) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TopologyMetadata) DecodeFromPtr(p capnp.Ptr) TopologyMetadata {
	return TopologyMetadata(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TopologyMetadata) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TopologyMetadata) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TopologyMetadata) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TopologyMetadata) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TopologyMetadata) TopologyFamily() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s TopologyMetadata) HasTopologyFamily() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TopologyMetadata) TopologyFamilyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s TopologyMetadata) SetTopologyFamily(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s TopologyMetadata) PartitionShape() (capnp.UInt32List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.UInt32List(p.List()), err
}

func (s TopologyMetadata) HasPartitionShape() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TopologyMetadata) SetPartitionShape(v capnp.UInt32List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewPartitionShape sets the partitionShape field to a newly
// allocated capnp.UInt32List, preferring placement in s's segment.
func (s TopologyMetadata) NewPartitionShape(n int32) (capnp.UInt32List, error) {
	l, err := capnp.NewUInt32List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt32List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// TopologyMetadata_List is a list of TopologyMetadata.
type TopologyMetadata_List = capnp.StructList[TopologyMetadata]

// NewTopologyMetadata creates a new list of TopologyMetadata.
func NewTopologyMetadata_List(s *capnp.Segment, sz int32) (TopologyMetadata_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[TopologyMetadata](l), err
}

// TopologyMetadata_Future is a wrapper for a TopologyMetadata promised by a client call.
type TopologyMetadata_Future struct{ *capnp.Future }

func (f TopologyMetadata_Future) Struct() (TopologyMetadata, error) {
	p, err := f.Future.Ptr()
	return TopologyMetadata(p.Struct()), err
}

type OptionalUInt32 capnp.Struct

// OptionalUInt32_TypeID is the unique identifier for the type OptionalUInt32.
const OptionalUInt32_TypeID = 0x83496be49a2be62e

func NewOptionalUInt32(s *capnp.Segment) (OptionalUInt32, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return OptionalUInt32(st), err
}

func NewRootOptionalUInt32(s *capnp.Segment) (OptionalUInt32, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return OptionalUInt32(st), err
}

func ReadRootOptionalUInt32(msg *capnp.Message) (OptionalUInt32, error) {
	root, err := msg.Root()
	return OptionalUInt32(root.Struct()), err
}

func (s OptionalUInt32) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (OptionalUInt32) DecodeFromPtr(p capnp.Ptr) OptionalUInt32 {
	return OptionalUInt32(capnp.Struct{}.DecodeFromPtr(p))
}

func (s OptionalUInt32) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s OptionalUInt32) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s OptionalUInt32) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s OptionalUInt32) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s OptionalUInt32) Value() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s OptionalUInt32) SetValue(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

// OptionalUInt32_List is a list of OptionalUInt32.
type OptionalUInt32_List = capnp.StructList[OptionalUInt32]

// NewOptionalUInt32 creates a new list of OptionalUInt32.
func NewOptionalUInt32_List(s *capnp.Segment, sz int32) (OptionalUInt32_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[OptionalUInt32](l), err
}

// OptionalUInt32_Future is a wrapper for a OptionalUInt32 promised by a client call.
type OptionalUInt32_Future struct{ *capnp.Future }

func (f OptionalUInt32_Future) Struct() (OptionalUInt32, error) {
	p, err := f.Future.Ptr()
	return OptionalUInt32(p.Struct()), err
}
