// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by lpx-scheduler. DO NOT EDIT.

// Package v1alpha1 contains the published LPX scheduling API types.
package v1alpha1
