// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by lpx-scheduler. DO NOT EDIT.

package v1alpha1

import (
	"fmt"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"unicode/utf8"
)

const (
	APIGroup   = "scheduling.lpu.nvidia.com"
	APIVersion = "v1alpha1"
)

var GroupVersion = schema.GroupVersion{Group: APIGroup, Version: APIVersion}

const (
	PodRoleAnnotation                = "scheduling.lpu.nvidia.com/role"
	PodModelAnnotation               = "scheduling.lpu.nvidia.com/model"
	CompilerSnapshotDigestAnnotation = "scheduling.lpu.nvidia.com/compiler-snapshot-digest"
	PodPartitionIDAnnotation         = "scheduling.lpu.nvidia.com/partition-id"
	PodRankInPartitionAnnotation     = "scheduling.lpu.nvidia.com/rank-in-partition"
	PodRoleAgent                     = "agent"
	PodRoleConductor                 = "conductor"
	PodRoleCyborgWorker              = "cyborg-worker"
	MaxModelAnnotationBytes          = 261054
)

func ParsePodRole(value string) (string, error) {
	switch value {
	case PodRoleAgent, PodRoleConductor, PodRoleCyborgWorker:
		return value, nil
	default:
		return "", fmt.Errorf("Pod role annotation %q is not an accepted producer role", value)
	}
}

func ValidateModelAnnotation(value string) error {
	if value == "" {
		return fmt.Errorf("model annotation must not be empty")
	}
	if !utf8.ValidString(value) {
		return fmt.Errorf("model annotation is not valid UTF-8")
	}
	if len(value) > MaxModelAnnotationBytes {
		return fmt.Errorf("model annotation contains %d UTF-8 bytes; at most %d are supported", len(value), MaxModelAnnotationBytes)
	}
	first, _ := utf8.DecodeRuneInString(value)
	last, _ := utf8.DecodeLastRuneInString(value)
	if isAnnotationBoundaryWhitespace(first) || isAnnotationBoundaryWhitespace(last) {
		return fmt.Errorf("model annotation %q has noncanonical boundary whitespace", value)
	}
	return nil
}

func isAnnotationBoundaryWhitespace(value rune) bool {
	switch {
	case value >= 0x0009 && value <= 0x000d:
		return true
	case value == 0x0020:
		return true
	case value == 0x0085:
		return true
	case value == 0x00a0:
		return true
	case value == 0x1680:
		return true
	case value >= 0x2000 && value <= 0x200a:
		return true
	case value >= 0x2028 && value <= 0x2029:
		return true
	case value == 0x202f:
		return true
	case value == 0x205f:
		return true
	case value == 0x3000:
		return true
	default:
		return false
	}
}

type LPUPipelineRequest struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              LPUPipelineRequestSpec    `json:"spec"`
	Status            *LPUPipelineRequestStatus `json:"status,omitempty"`
}

type LPUPipelineRequestList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LPUPipelineRequest `json:"items"`
}

type AtomicLPUMemberIdentity struct {
	Coordinate LPUFamilyCoordinate `json:"coordinate"`
	Device     ExactDeviceIdentity `json:"device"`
	FabricID   string              `json:"fabricId"`
}

func (in *AtomicLPUMemberIdentity) DeepCopyInto(out *AtomicLPUMemberIdentity) {
	*out = *in
	in.Coordinate.DeepCopyInto(&out.Coordinate)
	in.Device.DeepCopyInto(&out.Device)
}

func (in *AtomicLPUMemberIdentity) DeepCopy() *AtomicLPUMemberIdentity {
	if in == nil {
		return nil
	}
	out := new(AtomicLPUMemberIdentity)
	in.DeepCopyInto(out)
	return out
}

type BindingTarget struct {
	BindAttempt        *int64             `json:"bindAttempt,omitempty"`
	BindingRevision    int64              `json:"bindingRevision"`
	Phase              BindingTargetPhase `json:"phase"`
	PodRef             ObjectReference    `json:"podRef"`
	PodResourceVersion *string            `json:"podResourceVersion,omitempty"`
}

func (in *BindingTarget) DeepCopyInto(out *BindingTarget) {
	*out = *in
	if in.BindAttempt != nil {
		value := *in.BindAttempt
		out.BindAttempt = &value
	}
	in.PodRef.DeepCopyInto(&out.PodRef)
	if in.PodResourceVersion != nil {
		value := *in.PodResourceVersion
		out.PodResourceVersion = &value
	}
}

func (in *BindingTarget) DeepCopy() *BindingTarget {
	if in == nil {
		return nil
	}
	out := new(BindingTarget)
	in.DeepCopyInto(out)
	return out
}

type BindingTargetPhase string

const (
	BindingTargetPhaseRecorded         BindingTargetPhase = "recorded"
	BindingTargetPhaseClaimsAuthorized BindingTargetPhase = "claimsAuthorized"
	BindingTargetPhaseBindingAttempted BindingTargetPhase = "bindingAttempted"
	BindingTargetPhaseRetiring         BindingTargetPhase = "retiring"
)

type ClaimLifecyclePhase string

const (
	ClaimLifecyclePhaseRecorded  ClaimLifecyclePhase = "recorded"
	ClaimLifecyclePhaseAllocated ClaimLifecyclePhase = "allocated"
	ClaimLifecyclePhaseReleased  ClaimLifecyclePhase = "released"
)

type ClaimReference struct {
	Name string `json:"name"`
	UID  string `json:"uid"`
}

func (in *ClaimReference) DeepCopyInto(out *ClaimReference) {
	*out = *in
}

func (in *ClaimReference) DeepCopy() *ClaimReference {
	if in == nil {
		return nil
	}
	out := new(ClaimReference)
	in.DeepCopyInto(out)
	return out
}

type ClaimState struct {
	PartitionID string              `json:"partitionId"`
	Phase       ClaimLifecyclePhase `json:"phase"`
}

func (in *ClaimState) DeepCopyInto(out *ClaimState) {
	*out = *in
}

func (in *ClaimState) DeepCopy() *ClaimState {
	if in == nil {
		return nil
	}
	out := new(ClaimState)
	in.DeepCopyInto(out)
	return out
}

type CommitFence struct {
	ID      string             `json:"id"`
	Outcome CommitFenceOutcome `json:"outcome"`
}

func (in *CommitFence) DeepCopyInto(out *CommitFence) {
	*out = *in
}

func (in *CommitFence) DeepCopy() *CommitFence {
	if in == nil {
		return nil
	}
	out := new(CommitFence)
	in.DeepCopyInto(out)
	return out
}

type CommitFenceOutcome string

const (
	CommitFenceOutcomeCommitted CommitFenceOutcome = "committed"
	CommitFenceOutcomeAborted   CommitFenceOutcome = "aborted"
)

type Committed struct {
	Execution CommittedExecution `json:"execution"`
	Plan      CommittedPlan      `json:"plan"`
}

func (in *Committed) DeepCopyInto(out *Committed) {
	*out = *in
	in.Execution.DeepCopyInto(&out.Execution)
	in.Plan.DeepCopyInto(&out.Plan)
}

func (in *Committed) DeepCopy() *Committed {
	if in == nil {
		return nil
	}
	out := new(Committed)
	in.DeepCopyInto(out)
	return out
}

type CommittedExecution struct {
	AcceptedGeneration *int64              `json:"acceptedGeneration,omitempty"`
	NodeLocal          *NodeLocalExecution `json:"nodeLocal,omitempty"`
	Release            *ReleaseJournal     `json:"release,omitempty"`
	RemoteDra          *RemoteDraExecution `json:"remoteDra,omitempty"`
}

func (in *CommittedExecution) DeepCopyInto(out *CommittedExecution) {
	*out = *in
	if in.AcceptedGeneration != nil {
		value := *in.AcceptedGeneration
		out.AcceptedGeneration = &value
	}
	if in.NodeLocal != nil {
		out.NodeLocal = in.NodeLocal.DeepCopy()
	}
	if in.Release != nil {
		out.Release = in.Release.DeepCopy()
	}
	if in.RemoteDra != nil {
		out.RemoteDra = in.RemoteDra.DeepCopy()
	}
}

func (in *CommittedExecution) DeepCopy() *CommittedExecution {
	if in == nil {
		return nil
	}
	out := new(CommittedExecution)
	in.DeepCopyInto(out)
	return out
}

type CommittedPlan struct {
	Placement             PlanPlacement       `json:"placement"`
	PlanDigest            PlanDigest          `json:"planDigest"`
	PlannedFromGeneration int64               `json:"plannedFromGeneration"`
	RequestIntentDigest   RequestIntentDigest `json:"requestIntentDigest"`
	Revision              int64               `json:"revision"`
}

func (in *CommittedPlan) DeepCopyInto(out *CommittedPlan) {
	*out = *in
	in.Placement.DeepCopyInto(&out.Placement)
}

func (in *CommittedPlan) DeepCopy() *CommittedPlan {
	if in == nil {
		return nil
	}
	out := new(CommittedPlan)
	in.DeepCopyInto(out)
	return out
}

type ConnectorAssignment struct {
	FromPartitionID          string                       `json:"fromPartitionId"`
	FromSelectedMemberIDs    []string                     `json:"fromSelectedMemberIds"`
	HealthEvidence           ConnectorHealthEvidence      `json:"healthEvidence"`
	RealizedGap              *int64                       `json:"realizedGap,omitempty"`
	Requirement              PropSyncConnectorRequirement `json:"requirement"`
	SelectedLaneMultiplicity *int64                       `json:"selectedLaneMultiplicity,omitempty"`
	ToPartitionID            string                       `json:"toPartitionId"`
	ToSelectedMemberIDs      []string                     `json:"toSelectedMemberIds"`
}

func (in *ConnectorAssignment) DeepCopyInto(out *ConnectorAssignment) {
	*out = *in
	if in.FromSelectedMemberIDs != nil {
		out.FromSelectedMemberIDs = append(out.FromSelectedMemberIDs[:0:0], in.FromSelectedMemberIDs...)
	}
	in.HealthEvidence.DeepCopyInto(&out.HealthEvidence)
	if in.RealizedGap != nil {
		value := *in.RealizedGap
		out.RealizedGap = &value
	}
	in.Requirement.DeepCopyInto(&out.Requirement)
	if in.SelectedLaneMultiplicity != nil {
		value := *in.SelectedLaneMultiplicity
		out.SelectedLaneMultiplicity = &value
	}
	if in.ToSelectedMemberIDs != nil {
		out.ToSelectedMemberIDs = append(out.ToSelectedMemberIDs[:0:0], in.ToSelectedMemberIDs...)
	}
}

func (in *ConnectorAssignment) DeepCopy() *ConnectorAssignment {
	if in == nil {
		return nil
	}
	out := new(ConnectorAssignment)
	in.DeepCopyInto(out)
	return out
}

type ConnectorHealthEvidence struct {
	Identity string                `json:"identity"`
	Source   ConnectorHealthSource `json:"source"`
}

func (in *ConnectorHealthEvidence) DeepCopyInto(out *ConnectorHealthEvidence) {
	*out = *in
}

func (in *ConnectorHealthEvidence) DeepCopy() *ConnectorHealthEvidence {
	if in == nil {
		return nil
	}
	out := new(ConnectorHealthEvidence)
	in.DeepCopyInto(out)
	return out
}

type ConnectorHealthSource string

const (
	ConnectorHealthSourceGeneratedHealthyProfile ConnectorHealthSource = "generatedHealthyProfile"
)

type ConsumerBinding struct {
	ConsumerID string               `json:"consumerId"`
	Current    *CurrentBinding      `json:"current,omitempty"`
	PodClique  PodCliqueIncarnation `json:"podClique"`
	Target     *BindingTarget       `json:"target,omitempty"`
}

func (in *ConsumerBinding) DeepCopyInto(out *ConsumerBinding) {
	*out = *in
	if in.Current != nil {
		out.Current = in.Current.DeepCopy()
	}
	in.PodClique.DeepCopyInto(&out.PodClique)
	if in.Target != nil {
		out.Target = in.Target.DeepCopy()
	}
}

func (in *ConsumerBinding) DeepCopy() *ConsumerBinding {
	if in == nil {
		return nil
	}
	out := new(ConsumerBinding)
	in.DeepCopyInto(out)
	return out
}

type ConsumerRequest struct {
	ClaimNames   []string           `json:"claimNames"`
	EndpointID   *string            `json:"endpointId,omitempty"`
	ID           string             `json:"id"`
	PodCliqueRef PodCliqueReference `json:"podCliqueRef"`
}

func (in *ConsumerRequest) DeepCopyInto(out *ConsumerRequest) {
	*out = *in
	if in.ClaimNames != nil {
		out.ClaimNames = append(out.ClaimNames[:0:0], in.ClaimNames...)
	}
	if in.EndpointID != nil {
		value := *in.EndpointID
		out.EndpointID = &value
	}
	in.PodCliqueRef.DeepCopyInto(&out.PodCliqueRef)
}

func (in *ConsumerRequest) DeepCopy() *ConsumerRequest {
	if in == nil {
		return nil
	}
	out := new(ConsumerRequest)
	in.DeepCopyInto(out)
	return out
}

type ConsumerSlot struct {
	Claims                      []ClaimReference   `json:"claims"`
	ConsumerID                  string             `json:"consumerId"`
	EffectiveNodeRequests       map[string]int64   `json:"effectiveNodeRequests"`
	EndpointID                  string             `json:"endpointId"`
	NodeName                    string             `json:"nodeName"`
	PodCliqueRef                PodCliqueReference `json:"podCliqueRef"`
	SchedulingConstraintsDigest string             `json:"schedulingConstraintsDigest"`
}

func (in *ConsumerSlot) DeepCopyInto(out *ConsumerSlot) {
	*out = *in
	if in.Claims != nil {
		out.Claims = make([]ClaimReference, len(in.Claims))
		for i := range in.Claims {
			in.Claims[i].DeepCopyInto(&out.Claims[i])
		}
	}
	if in.EffectiveNodeRequests != nil {
		out.EffectiveNodeRequests = make(map[string]int64, len(in.EffectiveNodeRequests))
		for key, value := range in.EffectiveNodeRequests {
			out.EffectiveNodeRequests[key] = value
		}
	}
	in.PodCliqueRef.DeepCopyInto(&out.PodCliqueRef)
}

func (in *ConsumerSlot) DeepCopy() *ConsumerSlot {
	if in == nil {
		return nil
	}
	out := new(ConsumerSlot)
	in.DeepCopyInto(out)
	return out
}

type CurrentBinding struct {
	BindingRevision int64           `json:"bindingRevision"`
	PodRef          ObjectReference `json:"podRef"`
}

func (in *CurrentBinding) DeepCopyInto(out *CurrentBinding) {
	*out = *in
	in.PodRef.DeepCopyInto(&out.PodRef)
}

func (in *CurrentBinding) DeepCopy() *CurrentBinding {
	if in == nil {
		return nil
	}
	out := new(CurrentBinding)
	in.DeepCopyInto(out)
	return out
}

type DerivedStageAssignment struct {
	FabricID     string   `json:"fabricId"`
	ID           string   `json:"id"`
	Ordinal      int64    `json:"ordinal"`
	PartitionIDs []string `json:"partitionIds"`
}

func (in *DerivedStageAssignment) DeepCopyInto(out *DerivedStageAssignment) {
	*out = *in
	if in.PartitionIDs != nil {
		out.PartitionIDs = append(out.PartitionIDs[:0:0], in.PartitionIDs...)
	}
}

func (in *DerivedStageAssignment) DeepCopy() *DerivedStageAssignment {
	if in == nil {
		return nil
	}
	out := new(DerivedStageAssignment)
	in.DeepCopyInto(out)
	return out
}

type ExactDeviceIdentity struct {
	Device string `json:"device"`
	Driver string `json:"driver"`
	Pool   string `json:"pool"`
}

func (in *ExactDeviceIdentity) DeepCopyInto(out *ExactDeviceIdentity) {
	*out = *in
}

func (in *ExactDeviceIdentity) DeepCopy() *ExactDeviceIdentity {
	if in == nil {
		return nil
	}
	out := new(ExactDeviceIdentity)
	in.DeepCopyInto(out)
	return out
}

type ExecutionBackend string

const (
	ExecutionBackendRemoteDra ExecutionBackend = "remoteDra"
	ExecutionBackendNodeLocal ExecutionBackend = "nodeLocal"
)

type GroveSlotDigest string

type HxLogicalConnection struct {
	FromLogicalDevice int64 `json:"fromLogicalDevice"`
	ToLogicalDevice   int64 `json:"toLogicalDevice"`
}

func (in *HxLogicalConnection) DeepCopyInto(out *HxLogicalConnection) {
	*out = *in
}

func (in *HxLogicalConnection) DeepCopy() *HxLogicalConnection {
	if in == nil {
		return nil
	}
	out := new(HxLogicalConnection)
	in.DeepCopyInto(out)
	return out
}

type LPUFamilyCoordinate struct {
	Family     TargetFamily `json:"family"`
	Hemisphere *int64       `json:"hemisphere,omitempty"`
	Node       *int64       `json:"node,omitempty"`
	Rack       int64        `json:"rack"`
	Tray       *int64       `json:"tray,omitempty"`
}

func (in *LPUFamilyCoordinate) DeepCopyInto(out *LPUFamilyCoordinate) {
	*out = *in
	if in.Hemisphere != nil {
		value := *in.Hemisphere
		out.Hemisphere = &value
	}
	if in.Node != nil {
		value := *in.Node
		out.Node = &value
	}
	if in.Tray != nil {
		value := *in.Tray
		out.Tray = &value
	}
}

func (in *LPUFamilyCoordinate) DeepCopy() *LPUFamilyCoordinate {
	if in == nil {
		return nil
	}
	out := new(LPUFamilyCoordinate)
	in.DeepCopyInto(out)
	return out
}

type LPUPartitionPlacement struct {
	ClaimName       string                    `json:"claimName"`
	ClaimUID        string                    `json:"claimUid"`
	Family          TargetFamily              `json:"family"`
	OrderedMembers  []AtomicLPUMemberIdentity `json:"orderedMembers"`
	PartitionID     string                    `json:"partitionId"`
	RequestedExtent *[]int64                  `json:"requestedExtent,omitempty"`
	XtShape         *Xt8888PartitionShape     `json:"xtShape,omitempty"`
}

func (in *LPUPartitionPlacement) DeepCopyInto(out *LPUPartitionPlacement) {
	*out = *in
	if in.OrderedMembers != nil {
		out.OrderedMembers = make([]AtomicLPUMemberIdentity, len(in.OrderedMembers))
		for i := range in.OrderedMembers {
			in.OrderedMembers[i].DeepCopyInto(&out.OrderedMembers[i])
		}
	}
	if in.RequestedExtent != nil {
		value := make([]int64, len(*in.RequestedExtent))
		copy(value, *in.RequestedExtent)
		out.RequestedExtent = &value
	}
	if in.XtShape != nil {
		value := *in.XtShape
		out.XtShape = &value
	}
}

func (in *LPUPartitionPlacement) DeepCopy() *LPUPartitionPlacement {
	if in == nil {
		return nil
	}
	out := new(LPUPartitionPlacement)
	in.DeepCopyInto(out)
	return out
}

type LPUPipelineRequestSpec struct {
	AllocationMetadata    runtime.RawExtension       `json:"allocationMetadata"`
	CyborgPodCliqueRef    *PodCliqueReference        `json:"cyborgPodCliqueRef,omitempty"`
	ExecutionBackend      ExecutionBackend           `json:"executionBackend"`
	MaterializationTarget MaterializationTarget      `json:"materializationTarget"`
	NodeLocal             *NodeLocalRequest          `json:"nodeLocal,omitempty"`
	Partitions            []PartitionRequest         `json:"partitions"`
	PropSyncConnectors    []PropSyncConnectorRequest `json:"propSyncConnectors"`
	RemoteDra             *RemoteDraRequest          `json:"remoteDra,omitempty"`
	RepairPolicy          *RepairPolicy              `json:"repairPolicy,omitempty"`
	TargetFamily          TargetFamily               `json:"targetFamily"`
	WorkloadMode          WorkloadMode               `json:"workloadMode"`
}

func (in *LPUPipelineRequestSpec) DeepCopyInto(out *LPUPipelineRequestSpec) {
	*out = *in
	in.AllocationMetadata.DeepCopyInto(&out.AllocationMetadata)
	if in.CyborgPodCliqueRef != nil {
		out.CyborgPodCliqueRef = in.CyborgPodCliqueRef.DeepCopy()
	}
	in.MaterializationTarget.DeepCopyInto(&out.MaterializationTarget)
	if in.NodeLocal != nil {
		out.NodeLocal = in.NodeLocal.DeepCopy()
	}
	if in.Partitions != nil {
		out.Partitions = make([]PartitionRequest, len(in.Partitions))
		for i := range in.Partitions {
			in.Partitions[i].DeepCopyInto(&out.Partitions[i])
		}
	}
	if in.PropSyncConnectors != nil {
		out.PropSyncConnectors = make([]PropSyncConnectorRequest, len(in.PropSyncConnectors))
		for i := range in.PropSyncConnectors {
			in.PropSyncConnectors[i].DeepCopyInto(&out.PropSyncConnectors[i])
		}
	}
	if in.RemoteDra != nil {
		out.RemoteDra = in.RemoteDra.DeepCopy()
	}
	if in.RepairPolicy != nil {
		out.RepairPolicy = in.RepairPolicy.DeepCopy()
	}
}

func (in *LPUPipelineRequestSpec) DeepCopy() *LPUPipelineRequestSpec {
	if in == nil {
		return nil
	}
	out := new(LPUPipelineRequestSpec)
	in.DeepCopyInto(out)
	return out
}

type LPUPipelineRequestStatus struct {
	CommitFence                *CommitFence               `json:"commitFence,omitempty"`
	Committed                  *Committed                 `json:"committed,omitempty"`
	Conditions                 []metav1.Condition         `json:"conditions,omitempty"`
	Diagnostics                []StatusDiagnostic         `json:"diagnostics,omitempty"`
	LastAbortedPlanReplacement *PlanReplacementAbortFence `json:"lastAbortedPlanReplacement,omitempty"`
	LastPlanRevision           int64                      `json:"lastPlanRevision"`
	ObservedGeneration         *int64                     `json:"observedGeneration,omitempty"`
	Phase                      RequestPhase               `json:"phase"`
	SchedulingStartedAt        *metav1.Time               `json:"schedulingStartedAt,omitempty"`
}

func (in *LPUPipelineRequestStatus) DeepCopyInto(out *LPUPipelineRequestStatus) {
	*out = *in
	if in.CommitFence != nil {
		out.CommitFence = in.CommitFence.DeepCopy()
	}
	if in.Committed != nil {
		out.Committed = in.Committed.DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
	if in.Diagnostics != nil {
		out.Diagnostics = make([]StatusDiagnostic, len(in.Diagnostics))
		for i := range in.Diagnostics {
			in.Diagnostics[i].DeepCopyInto(&out.Diagnostics[i])
		}
	}
	if in.LastAbortedPlanReplacement != nil {
		value := *in.LastAbortedPlanReplacement
		out.LastAbortedPlanReplacement = &value
	}
	if in.ObservedGeneration != nil {
		value := *in.ObservedGeneration
		out.ObservedGeneration = &value
	}
	if in.SchedulingStartedAt != nil {
		out.SchedulingStartedAt = in.SchedulingStartedAt.DeepCopy()
	}
}

func (in *LPUPipelineRequestStatus) DeepCopy() *LPUPipelineRequestStatus {
	if in == nil {
		return nil
	}
	out := new(LPUPipelineRequestStatus)
	in.DeepCopyInto(out)
	return out
}

type MaterializationScope struct {
	CompilerSnapshotDigest   string                      `json:"compilerSnapshotDigest"`
	CyborgPodCliqueRef       *PodCliqueReference         `json:"cyborgPodCliqueRef,omitempty"`
	DynamoGraphDeploymentRef ObjectReference             `json:"dynamoGraphDeploymentRef"`
	PodCliqueScalingGroupRef *PodCliqueScalingGroupScope `json:"podCliqueScalingGroupRef,omitempty"`
	PodCliqueSetRef          ObjectReference             `json:"podCliqueSetRef"`
	PodCliqueSetReplicaIndex int64                       `json:"podCliqueSetReplicaIndex"`
}

func (in *MaterializationScope) DeepCopyInto(out *MaterializationScope) {
	*out = *in
	if in.CyborgPodCliqueRef != nil {
		out.CyborgPodCliqueRef = in.CyborgPodCliqueRef.DeepCopy()
	}
	in.DynamoGraphDeploymentRef.DeepCopyInto(&out.DynamoGraphDeploymentRef)
	if in.PodCliqueScalingGroupRef != nil {
		out.PodCliqueScalingGroupRef = in.PodCliqueScalingGroupRef.DeepCopy()
	}
	in.PodCliqueSetRef.DeepCopyInto(&out.PodCliqueSetRef)
}

func (in *MaterializationScope) DeepCopy() *MaterializationScope {
	if in == nil {
		return nil
	}
	out := new(MaterializationScope)
	in.DeepCopyInto(out)
	return out
}

type MaterializationTarget struct {
	PodCliqueScalingGroupRef *PodCliqueScalingGroupReference `json:"podCliqueScalingGroupRef,omitempty"`
	PodCliqueSetReplicaIndex int64                           `json:"podCliqueSetReplicaIndex"`
}

func (in *MaterializationTarget) DeepCopyInto(out *MaterializationTarget) {
	*out = *in
	if in.PodCliqueScalingGroupRef != nil {
		out.PodCliqueScalingGroupRef = in.PodCliqueScalingGroupRef.DeepCopy()
	}
}

func (in *MaterializationTarget) DeepCopy() *MaterializationTarget {
	if in == nil {
		return nil
	}
	out := new(MaterializationTarget)
	in.DeepCopyInto(out)
	return out
}

type NodeLocalConnectorEvidence struct {
	FromPartitionID          string                  `json:"fromPartitionId"`
	HealthEvidence           ConnectorHealthEvidence `json:"healthEvidence"`
	RealizedGap              *int64                  `json:"realizedGap,omitempty"`
	SelectedLaneMultiplicity *int64                  `json:"selectedLaneMultiplicity,omitempty"`
	ToPartitionID            string                  `json:"toPartitionId"`
}

func (in *NodeLocalConnectorEvidence) DeepCopyInto(out *NodeLocalConnectorEvidence) {
	*out = *in
	in.HealthEvidence.DeepCopyInto(&out.HealthEvidence)
	if in.RealizedGap != nil {
		value := *in.RealizedGap
		out.RealizedGap = &value
	}
	if in.SelectedLaneMultiplicity != nil {
		value := *in.SelectedLaneMultiplicity
		out.SelectedLaneMultiplicity = &value
	}
}

func (in *NodeLocalConnectorEvidence) DeepCopy() *NodeLocalConnectorEvidence {
	if in == nil {
		return nil
	}
	out := new(NodeLocalConnectorEvidence)
	in.DeepCopyInto(out)
	return out
}

type NodeLocalEndpoint struct {
	Coordinate  LPUFamilyCoordinate `json:"coordinate"`
	EndpointKey string              `json:"endpointKey"`
	FabricID    string              `json:"fabricId"`
}

func (in *NodeLocalEndpoint) DeepCopyInto(out *NodeLocalEndpoint) {
	*out = *in
	in.Coordinate.DeepCopyInto(&out.Coordinate)
}

func (in *NodeLocalEndpoint) DeepCopy() *NodeLocalEndpoint {
	if in == nil {
		return nil
	}
	out := new(NodeLocalEndpoint)
	in.DeepCopyInto(out)
	return out
}

type NodeLocalExecution struct {
	Materialization     NodeLocalMaterialization      `json:"materialization"`
	PartitionSelections []NodeLocalPartitionExecution `json:"partitionSelections"`
	PlanReplacement     *NodeLocalPlanReplacement     `json:"planReplacement,omitempty"`
}

func (in *NodeLocalExecution) DeepCopyInto(out *NodeLocalExecution) {
	*out = *in
	in.Materialization.DeepCopyInto(&out.Materialization)
	if in.PartitionSelections != nil {
		out.PartitionSelections = make([]NodeLocalPartitionExecution, len(in.PartitionSelections))
		for i := range in.PartitionSelections {
			in.PartitionSelections[i].DeepCopyInto(&out.PartitionSelections[i])
		}
	}
	if in.PlanReplacement != nil {
		out.PlanReplacement = in.PlanReplacement.DeepCopy()
	}
}

func (in *NodeLocalExecution) DeepCopy() *NodeLocalExecution {
	if in == nil {
		return nil
	}
	out := new(NodeLocalExecution)
	in.DeepCopyInto(out)
	return out
}

type NodeLocalMaterialization struct {
	Current NodeLocalMaterializationIncarnation  `json:"current"`
	Target  *NodeLocalMaterializationIncarnation `json:"target,omitempty"`
}

func (in *NodeLocalMaterialization) DeepCopyInto(out *NodeLocalMaterialization) {
	*out = *in
	in.Current.DeepCopyInto(&out.Current)
	if in.Target != nil {
		out.Target = in.Target.DeepCopy()
	}
}

func (in *NodeLocalMaterialization) DeepCopy() *NodeLocalMaterialization {
	if in == nil {
		return nil
	}
	out := new(NodeLocalMaterialization)
	in.DeepCopyInto(out)
	return out
}

type NodeLocalMaterializationIncarnation struct {
	AgentPodClique  PodCliqueIncarnation  `json:"agentPodClique"`
	CyborgPodClique *PodCliqueIncarnation `json:"cyborgPodClique,omitempty"`
}

func (in *NodeLocalMaterializationIncarnation) DeepCopyInto(out *NodeLocalMaterializationIncarnation) {
	*out = *in
	in.AgentPodClique.DeepCopyInto(&out.AgentPodClique)
	if in.CyborgPodClique != nil {
		out.CyborgPodClique = in.CyborgPodClique.DeepCopy()
	}
}

func (in *NodeLocalMaterializationIncarnation) DeepCopy() *NodeLocalMaterializationIncarnation {
	if in == nil {
		return nil
	}
	out := new(NodeLocalMaterializationIncarnation)
	in.DeepCopyInto(out)
	return out
}

type NodeLocalPartitionExecution struct {
	PartitionID  string                  `json:"partitionId"`
	SelectedRows []NodeLocalRowExecution `json:"selectedRows"`
}

func (in *NodeLocalPartitionExecution) DeepCopyInto(out *NodeLocalPartitionExecution) {
	*out = *in
	if in.SelectedRows != nil {
		out.SelectedRows = make([]NodeLocalRowExecution, len(in.SelectedRows))
		for i := range in.SelectedRows {
			in.SelectedRows[i].DeepCopyInto(&out.SelectedRows[i])
		}
	}
}

func (in *NodeLocalPartitionExecution) DeepCopy() *NodeLocalPartitionExecution {
	if in == nil {
		return nil
	}
	out := new(NodeLocalPartitionExecution)
	in.DeepCopyInto(out)
	return out
}

type NodeLocalPartitionMapping struct {
	ModelPartitionID int64  `json:"modelPartitionId"`
	PartitionID      string `json:"partitionId"`
}

func (in *NodeLocalPartitionMapping) DeepCopyInto(out *NodeLocalPartitionMapping) {
	*out = *in
}

func (in *NodeLocalPartitionMapping) DeepCopy() *NodeLocalPartitionMapping {
	if in == nil {
		return nil
	}
	out := new(NodeLocalPartitionMapping)
	in.DeepCopyInto(out)
	return out
}

type NodeLocalPartitionSelection struct {
	ModelPartitionID int64                  `json:"modelPartitionId"`
	PartitionID      string                 `json:"partitionId"`
	SelectedRows     []NodeLocalSelectedRow `json:"selectedRows"`
}

func (in *NodeLocalPartitionSelection) DeepCopyInto(out *NodeLocalPartitionSelection) {
	*out = *in
	if in.SelectedRows != nil {
		out.SelectedRows = make([]NodeLocalSelectedRow, len(in.SelectedRows))
		for i := range in.SelectedRows {
			in.SelectedRows[i].DeepCopyInto(&out.SelectedRows[i])
		}
	}
}

func (in *NodeLocalPartitionSelection) DeepCopy() *NodeLocalPartitionSelection {
	if in == nil {
		return nil
	}
	out := new(NodeLocalPartitionSelection)
	in.DeepCopyInto(out)
	return out
}

type NodeLocalPlacement struct {
	AgentPodCliqueRef              PodCliqueReference            `json:"agentPodCliqueRef"`
	CompilerMetadataDigest         string                        `json:"compilerMetadataDigest"`
	ConnectorEvidence              []NodeLocalConnectorEvidence  `json:"connectorEvidence,omitempty"`
	EffectiveNodeRequests          map[string]int64              `json:"effectiveNodeRequests"`
	InventoryRevision              string                        `json:"inventoryRevision"`
	Model                          string                        `json:"model"`
	NativeRepairBase               *string                       `json:"nativeRepairBase,omitempty"`
	Objective                      PlanObjective                 `json:"objective"`
	PartitionSelections            []NodeLocalPartitionSelection `json:"partitionSelections"`
	PodSchedulingDeclarationDigest string                        `json:"podSchedulingDeclarationDigest"`
	SchedulingConstraintsDigest    string                        `json:"schedulingConstraintsDigest"`
	WorkloadMode                   WorkloadMode                  `json:"workloadMode"`
}

func (in *NodeLocalPlacement) DeepCopyInto(out *NodeLocalPlacement) {
	*out = *in
	in.AgentPodCliqueRef.DeepCopyInto(&out.AgentPodCliqueRef)
	if in.ConnectorEvidence != nil {
		out.ConnectorEvidence = make([]NodeLocalConnectorEvidence, len(in.ConnectorEvidence))
		for i := range in.ConnectorEvidence {
			in.ConnectorEvidence[i].DeepCopyInto(&out.ConnectorEvidence[i])
		}
	}
	if in.EffectiveNodeRequests != nil {
		out.EffectiveNodeRequests = make(map[string]int64, len(in.EffectiveNodeRequests))
		for key, value := range in.EffectiveNodeRequests {
			out.EffectiveNodeRequests[key] = value
		}
	}
	if in.NativeRepairBase != nil {
		value := *in.NativeRepairBase
		out.NativeRepairBase = &value
	}
	in.Objective.DeepCopyInto(&out.Objective)
	if in.PartitionSelections != nil {
		out.PartitionSelections = make([]NodeLocalPartitionSelection, len(in.PartitionSelections))
		for i := range in.PartitionSelections {
			in.PartitionSelections[i].DeepCopyInto(&out.PartitionSelections[i])
		}
	}
}

func (in *NodeLocalPlacement) DeepCopy() *NodeLocalPlacement {
	if in == nil {
		return nil
	}
	out := new(NodeLocalPlacement)
	in.DeepCopyInto(out)
	return out
}

type NodeLocalPlanReplacement struct {
	BasePlanDigest   PlanDigest      `json:"basePlanDigest"`
	BasePlanRevision int64           `json:"basePlanRevision"`
	RealizeMembers   []RealizeMember `json:"realizeMembers"`
}

func (in *NodeLocalPlanReplacement) DeepCopyInto(out *NodeLocalPlanReplacement) {
	*out = *in
	if in.RealizeMembers != nil {
		out.RealizeMembers = make([]RealizeMember, len(in.RealizeMembers))
		for i := range in.RealizeMembers {
			in.RealizeMembers[i].DeepCopyInto(&out.RealizeMembers[i])
		}
	}
}

func (in *NodeLocalPlanReplacement) DeepCopy() *NodeLocalPlanReplacement {
	if in == nil {
		return nil
	}
	out := new(NodeLocalPlanReplacement)
	in.DeepCopyInto(out)
	return out
}

type NodeLocalRepairAuthorization struct {
	GroveSlotDigest GroveSlotDigest `json:"groveSlotDigest"`
}

func (in *NodeLocalRepairAuthorization) DeepCopyInto(out *NodeLocalRepairAuthorization) {
	*out = *in
}

func (in *NodeLocalRepairAuthorization) DeepCopy() *NodeLocalRepairAuthorization {
	if in == nil {
		return nil
	}
	out := new(NodeLocalRepairAuthorization)
	in.DeepCopyInto(out)
	return out
}

type NodeLocalRequest struct {
	AgentPodCliqueRef PodCliqueReference          `json:"agentPodCliqueRef"`
	Model             string                      `json:"model"`
	PartitionMappings []NodeLocalPartitionMapping `json:"partitionMappings"`
}

func (in *NodeLocalRequest) DeepCopyInto(out *NodeLocalRequest) {
	*out = *in
	in.AgentPodCliqueRef.DeepCopyInto(&out.AgentPodCliqueRef)
	if in.PartitionMappings != nil {
		out.PartitionMappings = make([]NodeLocalPartitionMapping, len(in.PartitionMappings))
		for i := range in.PartitionMappings {
			in.PartitionMappings[i].DeepCopyInto(&out.PartitionMappings[i])
		}
	}
}

func (in *NodeLocalRequest) DeepCopy() *NodeLocalRequest {
	if in == nil {
		return nil
	}
	out := new(NodeLocalRequest)
	in.DeepCopyInto(out)
	return out
}

type NodeLocalRowExecution struct {
	AdoptedTarget   bool                          `json:"adoptedTarget,omitempty"`
	Current         *CurrentBinding               `json:"current,omitempty"`
	RankInPartition int64                         `json:"rankInPartition"`
	Repair          *NodeLocalRepairAuthorization `json:"repair,omitempty"`
	Target          *BindingTarget                `json:"target,omitempty"`
}

func (in *NodeLocalRowExecution) DeepCopyInto(out *NodeLocalRowExecution) {
	*out = *in
	if in.Current != nil {
		out.Current = in.Current.DeepCopy()
	}
	if in.Repair != nil {
		out.Repair = in.Repair.DeepCopy()
	}
	if in.Target != nil {
		out.Target = in.Target.DeepCopy()
	}
}

func (in *NodeLocalRowExecution) DeepCopy() *NodeLocalRowExecution {
	if in == nil {
		return nil
	}
	out := new(NodeLocalRowExecution)
	in.DeepCopyInto(out)
	return out
}

type NodeLocalSelectedRow struct {
	Endpoint        NodeLocalEndpoint `json:"endpoint"`
	NodeRef         NodeReference     `json:"nodeRef"`
	RankInPartition int64             `json:"rankInPartition"`
}

func (in *NodeLocalSelectedRow) DeepCopyInto(out *NodeLocalSelectedRow) {
	*out = *in
	in.Endpoint.DeepCopyInto(&out.Endpoint)
	in.NodeRef.DeepCopyInto(&out.NodeRef)
}

func (in *NodeLocalSelectedRow) DeepCopy() *NodeLocalSelectedRow {
	if in == nil {
		return nil
	}
	out := new(NodeLocalSelectedRow)
	in.DeepCopyInto(out)
	return out
}

type NodeReference struct {
	Name string `json:"name"`
	UID  string `json:"uid"`
}

func (in *NodeReference) DeepCopyInto(out *NodeReference) {
	*out = *in
}

func (in *NodeReference) DeepCopy() *NodeReference {
	if in == nil {
		return nil
	}
	out := new(NodeReference)
	in.DeepCopyInto(out)
	return out
}

type ObjectReference struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
	UID       string `json:"uid"`
}

func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

type OldOnlyMember struct {
	Current     CurrentBinding    `json:"current"`
	OldEndpoint NodeLocalEndpoint `json:"oldEndpoint"`
	OldNodeRef  NodeReference     `json:"oldNodeRef"`
}

func (in *OldOnlyMember) DeepCopyInto(out *OldOnlyMember) {
	*out = *in
	in.Current.DeepCopyInto(&out.Current)
	in.OldEndpoint.DeepCopyInto(&out.OldEndpoint)
	in.OldNodeRef.DeepCopyInto(&out.OldNodeRef)
}

func (in *OldOnlyMember) DeepCopy() *OldOnlyMember {
	if in == nil {
		return nil
	}
	out := new(OldOnlyMember)
	in.DeepCopyInto(out)
	return out
}

type PartitionClaimRequest struct {
	ClaimName   string `json:"claimName"`
	PartitionID string `json:"partitionId"`
}

func (in *PartitionClaimRequest) DeepCopyInto(out *PartitionClaimRequest) {
	*out = *in
}

func (in *PartitionClaimRequest) DeepCopy() *PartitionClaimRequest {
	if in == nil {
		return nil
	}
	out := new(PartitionClaimRequest)
	in.DeepCopyInto(out)
	return out
}

type PartitionConductorAssignment struct {
	ClaimName   string `json:"claimName"`
	ConductorID string `json:"conductorId"`
	EndpointID  string `json:"endpointId"`
	PartitionID string `json:"partitionId"`
	StageID     string `json:"stageId"`
}

func (in *PartitionConductorAssignment) DeepCopyInto(out *PartitionConductorAssignment) {
	*out = *in
}

func (in *PartitionConductorAssignment) DeepCopy() *PartitionConductorAssignment {
	if in == nil {
		return nil
	}
	out := new(PartitionConductorAssignment)
	in.DeepCopyInto(out)
	return out
}

type PartitionRequest struct {
	CompilerPartitionID int64                 `json:"compilerPartitionId"`
	Extent              *[]int64              `json:"extent,omitempty"`
	ID                  string                `json:"id"`
	Ordinal             int64                 `json:"ordinal"`
	XtShape             *Xt8888PartitionShape `json:"xtShape,omitempty"`
}

func (in *PartitionRequest) DeepCopyInto(out *PartitionRequest) {
	*out = *in
	if in.Extent != nil {
		value := make([]int64, len(*in.Extent))
		copy(value, *in.Extent)
		out.Extent = &value
	}
	if in.XtShape != nil {
		value := *in.XtShape
		out.XtShape = &value
	}
}

func (in *PartitionRequest) DeepCopy() *PartitionRequest {
	if in == nil {
		return nil
	}
	out := new(PartitionRequest)
	in.DeepCopyInto(out)
	return out
}

type PlanDigest string

type PlanObjective struct {
	LoadImbalance           int64 `json:"loadImbalance"`
	NonPreferredAnchorCount int64 `json:"nonPreferredAnchorCount"`
	TraversalCost           int64 `json:"traversalCost"`
	UsedFabricPodCount      int64 `json:"usedFabricPodCount"`
}

func (in *PlanObjective) DeepCopyInto(out *PlanObjective) {
	*out = *in
}

func (in *PlanObjective) DeepCopy() *PlanObjective {
	if in == nil {
		return nil
	}
	out := new(PlanObjective)
	in.DeepCopyInto(out)
	return out
}

type PlanPlacement struct {
	ExecutionBackend     ExecutionBackend     `json:"executionBackend"`
	MaterializationScope MaterializationScope `json:"materializationScope"`
	NodeLocal            *NodeLocalPlacement  `json:"nodeLocal,omitempty"`
	RemoteDra            *RemoteDraPlacement  `json:"remoteDra,omitempty"`
}

func (in *PlanPlacement) DeepCopyInto(out *PlanPlacement) {
	*out = *in
	in.MaterializationScope.DeepCopyInto(&out.MaterializationScope)
	if in.NodeLocal != nil {
		out.NodeLocal = in.NodeLocal.DeepCopy()
	}
	if in.RemoteDra != nil {
		out.RemoteDra = in.RemoteDra.DeepCopy()
	}
}

func (in *PlanPlacement) DeepCopy() *PlanPlacement {
	if in == nil {
		return nil
	}
	out := new(PlanPlacement)
	in.DeepCopyInto(out)
	return out
}

type PlanReplacementAbortFence string

type PodCliqueIncarnation struct {
	PodTemplateHash string `json:"podTemplateHash"`
	UID             string `json:"uid"`
}

func (in *PodCliqueIncarnation) DeepCopyInto(out *PodCliqueIncarnation) {
	*out = *in
}

func (in *PodCliqueIncarnation) DeepCopy() *PodCliqueIncarnation {
	if in == nil {
		return nil
	}
	out := new(PodCliqueIncarnation)
	in.DeepCopyInto(out)
	return out
}

type PodCliqueReference struct {
	Name string `json:"name"`
}

func (in *PodCliqueReference) DeepCopyInto(out *PodCliqueReference) {
	*out = *in
}

func (in *PodCliqueReference) DeepCopy() *PodCliqueReference {
	if in == nil {
		return nil
	}
	out := new(PodCliqueReference)
	in.DeepCopyInto(out)
	return out
}

type PodCliqueScalingGroupReference struct {
	Name         string `json:"name"`
	ReplicaIndex int64  `json:"replicaIndex"`
}

func (in *PodCliqueScalingGroupReference) DeepCopyInto(out *PodCliqueScalingGroupReference) {
	*out = *in
}

func (in *PodCliqueScalingGroupReference) DeepCopy() *PodCliqueScalingGroupReference {
	if in == nil {
		return nil
	}
	out := new(PodCliqueScalingGroupReference)
	in.DeepCopyInto(out)
	return out
}

type PodCliqueScalingGroupScope struct {
	Name         string `json:"name"`
	ReplicaIndex int64  `json:"replicaIndex"`
	SpecDigest   string `json:"specDigest"`
	UID          string `json:"uid"`
}

func (in *PodCliqueScalingGroupScope) DeepCopyInto(out *PodCliqueScalingGroupScope) {
	*out = *in
}

func (in *PodCliqueScalingGroupScope) DeepCopy() *PodCliqueScalingGroupScope {
	if in == nil {
		return nil
	}
	out := new(PodCliqueScalingGroupScope)
	in.DeepCopyInto(out)
	return out
}

type PropSyncConnectorKind string

const (
	PropSyncConnectorKindHxPropSyncV1 PropSyncConnectorKind = "hxPropSyncV1"
	PropSyncConnectorKindXt8888Gap    PropSyncConnectorKind = "xt8888Gap"
)

type PropSyncConnectorRequest struct {
	FromPartitionID string                       `json:"fromPartitionId"`
	Requirement     PropSyncConnectorRequirement `json:"requirement"`
	ToPartitionID   string                       `json:"toPartitionId"`
}

func (in *PropSyncConnectorRequest) DeepCopyInto(out *PropSyncConnectorRequest) {
	*out = *in
	in.Requirement.DeepCopyInto(&out.Requirement)
}

func (in *PropSyncConnectorRequest) DeepCopy() *PropSyncConnectorRequest {
	if in == nil {
		return nil
	}
	out := new(PropSyncConnectorRequest)
	in.DeepCopyInto(out)
	return out
}

type PropSyncConnectorRequirement struct {
	AcceptableLaneMultiplicities *[]int64               `json:"acceptableLaneMultiplicities,omitempty"`
	Connections                  *[]HxLogicalConnection `json:"connections,omitempty"`
	Kind                         PropSyncConnectorKind  `json:"kind"`
	MaxInterPartitionOffset      *int64                 `json:"maxInterPartitionOffset,omitempty"`
}

func (in *PropSyncConnectorRequirement) DeepCopyInto(out *PropSyncConnectorRequirement) {
	*out = *in
	if in.AcceptableLaneMultiplicities != nil {
		value := make([]int64, len(*in.AcceptableLaneMultiplicities))
		copy(value, *in.AcceptableLaneMultiplicities)
		out.AcceptableLaneMultiplicities = &value
	}
	if in.Connections != nil {
		value := make([]HxLogicalConnection, len(*in.Connections))
		copy(value, *in.Connections)
		out.Connections = &value
	}
	if in.MaxInterPartitionOffset != nil {
		value := *in.MaxInterPartitionOffset
		out.MaxInterPartitionOffset = &value
	}
}

func (in *PropSyncConnectorRequirement) DeepCopy() *PropSyncConnectorRequirement {
	if in == nil {
		return nil
	}
	out := new(PropSyncConnectorRequirement)
	in.DeepCopyInto(out)
	return out
}

type RealizeMember struct {
	GroveSlotDigest     GroveSlotDigest          `json:"groveSlotDigest"`
	NextBindingRevision int64                    `json:"nextBindingRevision"`
	PartitionID         string                   `json:"partitionId"`
	Predecessor         RealizeMemberPredecessor `json:"predecessor"`
	RankInPartition     int64                    `json:"rankInPartition"`
}

func (in *RealizeMember) DeepCopyInto(out *RealizeMember) {
	*out = *in
	in.Predecessor.DeepCopyInto(&out.Predecessor)
}

func (in *RealizeMember) DeepCopy() *RealizeMember {
	if in == nil {
		return nil
	}
	out := new(RealizeMember)
	in.DeepCopyInto(out)
	return out
}

type RealizeMemberPredecessor struct {
	OldOnly *OldOnlyMember                `json:"oldOnly,omitempty"`
	Phase   RealizeMemberPredecessorPhase `json:"phase"`
}

func (in *RealizeMemberPredecessor) DeepCopyInto(out *RealizeMemberPredecessor) {
	*out = *in
	if in.OldOnly != nil {
		out.OldOnly = in.OldOnly.DeepCopy()
	}
}

func (in *RealizeMemberPredecessor) DeepCopy() *RealizeMemberPredecessor {
	if in == nil {
		return nil
	}
	out := new(RealizeMemberPredecessor)
	in.DeepCopyInto(out)
	return out
}

type RealizeMemberPredecessorPhase string

const (
	RealizeMemberPredecessorPhaseProtected  RealizeMemberPredecessorPhase = "protected"
	RealizeMemberPredecessorPhaseAuthorized RealizeMemberPredecessorPhase = "authorized"
	RealizeMemberPredecessorPhaseRetired    RealizeMemberPredecessorPhase = "retired"
)

type ReleaseJournal struct {
	Reason                ReleaseReason `json:"reason"`
	RequestedAtGeneration int64         `json:"requestedAtGeneration"`
}

func (in *ReleaseJournal) DeepCopyInto(out *ReleaseJournal) {
	*out = *in
}

func (in *ReleaseJournal) DeepCopy() *ReleaseJournal {
	if in == nil {
		return nil
	}
	out := new(ReleaseJournal)
	in.DeepCopyInto(out)
	return out
}

type ReleaseReason string

const (
	ReleaseReasonRequestChanged    ReleaseReason = "requestChanged"
	ReleaseReasonRequestDeleted    ReleaseReason = "requestDeleted"
	ReleaseReasonDependencyChanged ReleaseReason = "dependencyChanged"
	ReleaseReasonBindingFailed     ReleaseReason = "bindingFailed"
)

type RemoteDraExecution struct {
	ClaimStates      []ClaimState      `json:"claimStates"`
	ConsumerBindings []ConsumerBinding `json:"consumerBindings"`
}

func (in *RemoteDraExecution) DeepCopyInto(out *RemoteDraExecution) {
	*out = *in
	if in.ClaimStates != nil {
		out.ClaimStates = make([]ClaimState, len(in.ClaimStates))
		for i := range in.ClaimStates {
			in.ClaimStates[i].DeepCopyInto(&out.ClaimStates[i])
		}
	}
	if in.ConsumerBindings != nil {
		out.ConsumerBindings = make([]ConsumerBinding, len(in.ConsumerBindings))
		for i := range in.ConsumerBindings {
			in.ConsumerBindings[i].DeepCopyInto(&out.ConsumerBindings[i])
		}
	}
}

func (in *RemoteDraExecution) DeepCopy() *RemoteDraExecution {
	if in == nil {
		return nil
	}
	out := new(RemoteDraExecution)
	in.DeepCopyInto(out)
	return out
}

type RemoteDraPlacement struct {
	ActiveFabricIDs        *[]string                      `json:"activeFabricIds,omitempty"`
	CompilerMetadataDigest string                         `json:"compilerMetadataDigest"`
	ConnectorAssignments   []ConnectorAssignment          `json:"connectorAssignments,omitempty"`
	ConsumerSlots          []ConsumerSlot                 `json:"consumerSlots"`
	DerivedStages          []DerivedStageAssignment       `json:"derivedStages"`
	InventoryRevision      string                         `json:"inventoryRevision"`
	Objective              PlanObjective                  `json:"objective"`
	PartitionConductors    []PartitionConductorAssignment `json:"partitionConductors"`
	PartitionPlacements    []LPUPartitionPlacement        `json:"partitionPlacements"`
	WorkloadMode           WorkloadMode                   `json:"workloadMode"`
}

func (in *RemoteDraPlacement) DeepCopyInto(out *RemoteDraPlacement) {
	*out = *in
	if in.ActiveFabricIDs != nil {
		value := make([]string, len(*in.ActiveFabricIDs))
		copy(value, *in.ActiveFabricIDs)
		out.ActiveFabricIDs = &value
	}
	if in.ConnectorAssignments != nil {
		out.ConnectorAssignments = make([]ConnectorAssignment, len(in.ConnectorAssignments))
		for i := range in.ConnectorAssignments {
			in.ConnectorAssignments[i].DeepCopyInto(&out.ConnectorAssignments[i])
		}
	}
	if in.ConsumerSlots != nil {
		out.ConsumerSlots = make([]ConsumerSlot, len(in.ConsumerSlots))
		for i := range in.ConsumerSlots {
			in.ConsumerSlots[i].DeepCopyInto(&out.ConsumerSlots[i])
		}
	}
	if in.DerivedStages != nil {
		out.DerivedStages = make([]DerivedStageAssignment, len(in.DerivedStages))
		for i := range in.DerivedStages {
			in.DerivedStages[i].DeepCopyInto(&out.DerivedStages[i])
		}
	}
	in.Objective.DeepCopyInto(&out.Objective)
	if in.PartitionConductors != nil {
		out.PartitionConductors = make([]PartitionConductorAssignment, len(in.PartitionConductors))
		for i := range in.PartitionConductors {
			in.PartitionConductors[i].DeepCopyInto(&out.PartitionConductors[i])
		}
	}
	if in.PartitionPlacements != nil {
		out.PartitionPlacements = make([]LPUPartitionPlacement, len(in.PartitionPlacements))
		for i := range in.PartitionPlacements {
			in.PartitionPlacements[i].DeepCopyInto(&out.PartitionPlacements[i])
		}
	}
}

func (in *RemoteDraPlacement) DeepCopy() *RemoteDraPlacement {
	if in == nil {
		return nil
	}
	out := new(RemoteDraPlacement)
	in.DeepCopyInto(out)
	return out
}

type RemoteDraRequest struct {
	Consumers       []ConsumerRequest       `json:"consumers"`
	PartitionClaims []PartitionClaimRequest `json:"partitionClaims"`
}

func (in *RemoteDraRequest) DeepCopyInto(out *RemoteDraRequest) {
	*out = *in
	if in.Consumers != nil {
		out.Consumers = make([]ConsumerRequest, len(in.Consumers))
		for i := range in.Consumers {
			in.Consumers[i].DeepCopyInto(&out.Consumers[i])
		}
	}
	if in.PartitionClaims != nil {
		out.PartitionClaims = make([]PartitionClaimRequest, len(in.PartitionClaims))
		for i := range in.PartitionClaims {
			in.PartitionClaims[i].DeepCopyInto(&out.PartitionClaims[i])
		}
	}
}

func (in *RemoteDraRequest) DeepCopy() *RemoteDraRequest {
	if in == nil {
		return nil
	}
	out := new(RemoteDraRequest)
	in.DeepCopyInto(out)
	return out
}

type RepairPolicy struct {
	Mode RepairPolicyMode `json:"mode"`
}

func (in *RepairPolicy) DeepCopyInto(out *RepairPolicy) {
	*out = *in
}

func (in *RepairPolicy) DeepCopy() *RepairPolicy {
	if in == nil {
		return nil
	}
	out := new(RepairPolicy)
	in.DeepCopyInto(out)
	return out
}

type RepairPolicyMode string

const (
	RepairPolicyModeColdReplacement RepairPolicyMode = "coldReplacement"
	RepairPolicyModeSamePlacement   RepairPolicyMode = "samePlacement"
	RepairPolicyModeRepair          RepairPolicyMode = "repair"
)

type RequestIntentDigest string

type RequestPhase string

const (
	RequestPhasePending     RequestPhase = "pending"
	RequestPhaseNoFit       RequestPhase = "noFit"
	RequestPhaseUnsupported RequestPhase = "unsupported"
	RequestPhasePlanned     RequestPhase = "planned"
	RequestPhaseReserving   RequestPhase = "reserving"
	RequestPhaseBinding     RequestPhase = "binding"
	RequestPhaseBound       RequestPhase = "bound"
	RequestPhaseDegraded    RequestPhase = "degraded"
	RequestPhaseReleasing   RequestPhase = "releasing"
	RequestPhaseReleased    RequestPhase = "released"
)

type StatusDiagnostic struct {
	Code    string `json:"code"`
	Detail  string `json:"detail"`
	Subject string `json:"subject"`
}

func (in *StatusDiagnostic) DeepCopyInto(out *StatusDiagnostic) {
	*out = *in
}

func (in *StatusDiagnostic) DeepCopy() *StatusDiagnostic {
	if in == nil {
		return nil
	}
	out := new(StatusDiagnostic)
	in.DeepCopyInto(out)
	return out
}

type TargetFamily string

const (
	TargetFamilyXt8888     TargetFamily = "xt8888"
	TargetFamilyHx16x8x2x3 TargetFamily = "hx16x8x2x3"
)

type WorkloadMode string

const (
	WorkloadModeV2LPUOnly        WorkloadMode = "v2LpuOnly"
	WorkloadModeV2StrictHybrid   WorkloadMode = "v2StrictHybrid"
	WorkloadModeV3HxLPUOnly      WorkloadMode = "v3HxLpuOnly"
	WorkloadModeV3HxStrictHybrid WorkloadMode = "v3HxStrictHybrid"
)

type Xt8888PartitionShape string

const (
	Xt8888PartitionShapeC8   Xt8888PartitionShape = "c8"
	Xt8888PartitionShapeC16  Xt8888PartitionShape = "c16"
	Xt8888PartitionShapeC24  Xt8888PartitionShape = "c24"
	Xt8888PartitionShapeC32  Xt8888PartitionShape = "c32"
	Xt8888PartitionShapeC40  Xt8888PartitionShape = "c40"
	Xt8888PartitionShapeC48  Xt8888PartitionShape = "c48"
	Xt8888PartitionShapeC56  Xt8888PartitionShape = "c56"
	Xt8888PartitionShapeC64  Xt8888PartitionShape = "c64"
	Xt8888PartitionShapeC96  Xt8888PartitionShape = "c96"
	Xt8888PartitionShapeC128 Xt8888PartitionShape = "c128"
)

var SchemeBuilder = runtime.NewSchemeBuilder(func(scheme *runtime.Scheme) error {
	scheme.AddKnownTypeWithName(GroupVersion.WithKind("LpuPipelineRequest"), &LPUPipelineRequest{})
	scheme.AddKnownTypeWithName(GroupVersion.WithKind("LpuPipelineRequestList"), &LPUPipelineRequestList{})
	metav1.AddToGroupVersion(scheme, GroupVersion)
	return nil
})

var AddToScheme = SchemeBuilder.AddToScheme

func (in *LPUPipelineRequest) DeepCopyInto(out *LPUPipelineRequest) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		out.Status = in.Status.DeepCopy()
	}
}

func (in *LPUPipelineRequest) DeepCopy() *LPUPipelineRequest {
	if in == nil {
		return nil
	}
	out := new(LPUPipelineRequest)
	in.DeepCopyInto(out)
	return out
}

func (in *LPUPipelineRequest) DeepCopyObject() runtime.Object {
	if copied := in.DeepCopy(); copied != nil {
		return copied
	}
	return nil
}

func (in *LPUPipelineRequestList) DeepCopyInto(out *LPUPipelineRequestList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]LPUPipelineRequest, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *LPUPipelineRequestList) DeepCopy() *LPUPipelineRequestList {
	if in == nil {
		return nil
	}
	out := new(LPUPipelineRequestList)
	in.DeepCopyInto(out)
	return out
}

func (in *LPUPipelineRequestList) DeepCopyObject() runtime.Object {
	if copied := in.DeepCopy(); copied != nil {
		return copied
	}
	return nil
}
